// <auto-generated />
// Generated from build/loc/strings.json by build/generate-localization.ps1. Do not edit.

namespace GitVault.Localization;

/// <summary>Every resource key defined by GitVault, as compile-time constants.</summary>
public static class Keys
{
    /// <summary>English: GitVault</summary>
    public const string App_Title = "App_Title";

    /// <summary>English: Git accounts, keys and credentials</summary>
    public const string App_Subtitle = "App_Subtitle";

    /// <summary>English: {0} — {1}</summary>
    public const string App_WindowTitle = "App_WindowTitle";

    /// <summary>English: Dashboard</summary>
    public const string Nav_Dashboard = "Nav_Dashboard";

    /// <summary>English: Identities</summary>
    public const string Nav_Identities = "Nav_Identities";

    /// <summary>English: SSH keys</summary>
    public const string Nav_Keys = "Nav_Keys";

    /// <summary>English: Agents</summary>
    public const string Nav_Agents = "Nav_Agents";

    /// <summary>English: Credentials</summary>
    public const string Nav_Credentials = "Nav_Credentials";

    /// <summary>English: Clients</summary>
    public const string Nav_Clients = "Nav_Clients";

    /// <summary>English: Profiles</summary>
    public const string Nav_Profiles = "Nav_Profiles";

    /// <summary>English: Repositories</summary>
    public const string Nav_Repositories = "Nav_Repositories";

    /// <summary>English: Settings</summary>
    public const string Nav_Settings = "Nav_Settings";

    /// <summary>English: Logs</summary>
    public const string Nav_Logs = "Nav_Logs";

    /// <summary>English: Rescan</summary>
    public const string Common_Rescan = "Common_Rescan";

    /// <summary>English: Search</summary>
    public const string Common_Search = "Common_Search";

    /// <summary>English: Cancel</summary>
    public const string Common_Cancel = "Common_Cancel";

    /// <summary>English: OK</summary>
    public const string Common_Ok = "Common_Ok";

    /// <summary>English: Close</summary>
    public const string Common_Close = "Common_Close";

    /// <summary>English: Copy</summary>
    public const string Common_Copy = "Common_Copy";

    /// <summary>English: Apply</summary>
    public const string Common_Apply = "Common_Apply";

    /// <summary>English: Working…</summary>
    public const string Common_Working = "Common_Working";

    /// <summary>English: Nothing to show</summary>
    public const string Common_NoData = "Common_NoData";

    /// <summary>English: Details</summary>
    public const string Common_Details = "Common_Details";

    /// <summary>English: What does this mean?</summary>
    public const string Common_WhatDoesThisMean = "Common_WhatDoesThisMean";

    /// <summary>English: Yes</summary>
    public const string Common_Yes = "Common_Yes";

    /// <summary>English: No</summary>
    public const string Common_No = "Common_No";

    /// <summary>English: Never</summary>
    public const string Common_Never = "Common_Never";

    /// <summary>English: , </summary>
    public const string Common_ListSeparator = "Common_ListSeparator";

    /// <summary>English: Dashboard</summary>
    public const string Dashboard_Title = "Dashboard_Title";

    /// <summary>English: Everything GitVault found on this machine</summary>
    public const string Dashboard_Subtitle = "Dashboard_Subtitle";

    /// <summary>English: Identities</summary>
    public const string Dashboard_Card_Identities = "Dashboard_Card_Identities";

    /// <summary>English: SSH keys</summary>
    public const string Dashboard_Card_Keys = "Dashboard_Card_Keys";

    /// <summary>English: Agents</summary>
    public const string Dashboard_Card_Agents = "Dashboard_Card_Agents";

    /// <summary>English: Credentials</summary>
    public const string Dashboard_Card_Credentials = "Dashboard_Card_Credentials";

    /// <summary>English: Clients</summary>
    public const string Dashboard_Card_Clients = "Dashboard_Card_Clients";

    /// <summary>English: Active global identity</summary>
    public const string Dashboard_ActiveIdentity = "Dashboard_ActiveIdentity";

    /// <summary>English: No scan has run yet</summary>
    public const string Dashboard_NoScanYet = "Dashboard_NoScanYet";

    /// <summary>English: Fix all safe issues</summary>
    public const string Dashboard_FixAllSafe = "Dashboard_FixAllSafe";

    /// <summary>English: Health warnings</summary>
    public const string Dashboard_Warnings = "Dashboard_Warnings";

    /// <summary>English: Scan finished in {0} ms</summary>
    public const string Dashboard_ScanDuration = "Dashboard_ScanDuration";

    /// <summary>English: Probe status</summary>
    public const string Dashboard_ProbeMatrix = "Dashboard_ProbeMatrix";

    /// <summary>English: Operating system</summary>
    public const string Dashboard_Env_Os = "Dashboard_Env_Os";

    /// <summary>English: Architecture</summary>
    public const string Dashboard_Env_Cpu = "Dashboard_Env_Cpu";

    /// <summary>English: GitVault data folder</summary>
    public const string Dashboard_Env_AppData = "Dashboard_Env_AppData";

    /// <summary>English: Git executable</summary>
    public const string Dashboard_Env_Git = "Dashboard_Env_Git";

    /// <summary>English: {0} (version {1})</summary>
    public const string Dashboard_Env_GitPathAndVersion = "Dashboard_Env_GitPathAndVersion";

    /// <summary>English: Scanning…</summary>
    public const string Dashboard_Scanning = "Dashboard_Scanning";

    /// <summary>English: Identities</summary>
    public const string Identities_Title = "Identities_Title";

    /// <summary>English: Name</summary>
    public const string Identities_Column_Name = "Identities_Column_Name";

    /// <summary>English: E-mail</summary>
    public const string Identities_Column_Email = "Identities_Column_Email";

    /// <summary>English: Source</summary>
    public const string Identities_Column_Source = "Identities_Column_Source";

    /// <summary>English: Hosts</summary>
    public const string Identities_Column_Hosts = "Identities_Column_Hosts";

    /// <summary>English: Scope</summary>
    public const string Identities_Column_Scope = "Identities_Column_Scope";

    /// <summary>English: Confidence</summary>
    public const string Identities_Column_Confidence = "Identities_Column_Confidence";

    /// <summary>English: Signing key</summary>
    public const string Identities_Column_SigningKey = "Identities_Column_SigningKey";

    /// <summary>English: No identities found</summary>
    public const string Identities_Empty = "Identities_Empty";

    /// <summary>English: In effect for this user</summary>
    public const string Identities_Effective_Title = "Identities_Effective_Title";

    /// <summary>English: Setting</summary>
    public const string Identities_Effective_Key = "Identities_Effective_Key";

    /// <summary>English: Value</summary>
    public const string Identities_Effective_Value = "Identities_Effective_Value";

    /// <summary>English: Set in</summary>
    public const string Identities_Effective_WinningScope = "Identities_Effective_WinningScope";

    /// <summary>English: not set</summary>
    public const string Identities_Effective_Unset = "Identities_Effective_Unset";

    /// <summary>English: overrides {0}</summary>
    public const string Identities_Effective_OverriddenIn = "Identities_Effective_OverriddenIn";

    /// <summary>English: Seen in</summary>
    public const string Identities_Detail_Occurrences = "Identities_Detail_Occurrences";

    /// <summary>English: System</summary>
    public const string Scope_System = "Scope_System";

    /// <summary>English: Global</summary>
    public const string Scope_Global = "Scope_Global";

    /// <summary>English: Repository</summary>
    public const string Scope_Local = "Scope_Local";

    /// <summary>English: Worktree</summary>
    public const string Scope_Worktree = "Scope_Worktree";

    /// <summary>English: Command line</summary>
    public const string Scope_Command = "Scope_Command";

    /// <summary>English: Unknown</summary>
    public const string Scope_Unknown = "Scope_Unknown";

    /// <summary>English: Certain</summary>
    public const string Confidence_Certain = "Confidence_Certain";

    /// <summary>English: Probable</summary>
    public const string Confidence_Probable = "Confidence_Probable";

    /// <summary>English: Guessed</summary>
    public const string Confidence_Heuristic = "Confidence_Heuristic";

    /// <summary>English: System git config</summary>
    public const string Source_GitSystemConfig = "Source_GitSystemConfig";

    /// <summary>English: User git config</summary>
    public const string Source_GitGlobalConfig = "Source_GitGlobalConfig";

    /// <summary>English: Repository config</summary>
    public const string Source_RepoLocal = "Source_RepoLocal";

    /// <summary>English: Worktree config</summary>
    public const string Source_RepoWorktree = "Source_RepoWorktree";

    /// <summary>English: Included file</summary>
    public const string Source_GitIncludedFile = "Source_GitIncludedFile";

    /// <summary>English: Unknown source</summary>
    public const string Source_Unknown = "Source_Unknown";

    /// <summary>English: SSH keys</summary>
    public const string Keys_Title = "Keys_Title";

    /// <summary>English: Algorithm</summary>
    public const string Keys_Column_Algorithm = "Keys_Column_Algorithm";

    /// <summary>English: Fingerprint</summary>
    public const string Keys_Column_Fingerprint = "Keys_Column_Fingerprint";

    /// <summary>English: Comment</summary>
    public const string Keys_Column_Comment = "Keys_Column_Comment";

    /// <summary>English: Path</summary>
    public const string Keys_Column_Path = "Keys_Column_Path";

    /// <summary>English: Format</summary>
    public const string Keys_Column_Format = "Keys_Column_Format";

    /// <summary>English: Passphrase protected</summary>
    public const string Keys_Encrypted = "Keys_Encrypted";

    /// <summary>English: No passphrase</summary>
    public const string Keys_NotEncrypted = "Keys_NotEncrypted";

    /// <summary>English: Loaded in agent</summary>
    public const string Keys_InAgent = "Keys_InAgent";

    /// <summary>English: No SSH keys found</summary>
    public const string Keys_Empty = "Keys_Empty";

    /// <summary>English: Bits</summary>
    public const string Keys_Column_Bits = "Keys_Column_Bits";

    /// <summary>English: Protection</summary>
    public const string Keys_Column_Protection = "Keys_Column_Protection";

    /// <summary>English: Public key</summary>
    public const string Keys_Detail_PublicKey = "Keys_Detail_PublicKey";

    /// <summary>English: File mode</summary>
    public const string Keys_Detail_Permissions = "Keys_Detail_Permissions";

    /// <summary>English: KDF rounds</summary>
    public const string Keys_Detail_KdfRounds = "Keys_Detail_KdfRounds";

    /// <summary>English: Hardware-backed</summary>
    public const string Keys_Hardware = "Keys_Hardware";

    /// <summary>English: Copy public key</summary>
    public const string Keys_CopyPublicKey = "Keys_CopyPublicKey";

    /// <summary>English: Copy fingerprint</summary>
    public const string Keys_CopyFingerprint = "Keys_CopyFingerprint";

    /// <summary>English: Show in file manager</summary>
    public const string Keys_RevealInFileManager = "Keys_RevealInFileManager";

    /// <summary>English: Copied to the clipboard</summary>
    public const string Keys_Copied = "Keys_Copied";

    /// <summary>English: OpenSSH</summary>
    public const string Format_OpenSsh = "Format_OpenSsh";

    /// <summary>English: PEM</summary>
    public const string Format_Pem = "Format_Pem";

    /// <summary>English: PKCS#8</summary>
    public const string Format_Pkcs8 = "Format_Pkcs8";

    /// <summary>English: PuTTY v2</summary>
    public const string Format_Ppk2 = "Format_Ppk2";

    /// <summary>English: PuTTY v3</summary>
    public const string Format_Ppk3 = "Format_Ppk3";

    /// <summary>English: Public key only</summary>
    public const string Format_PublicOnly = "Format_PublicOnly";

    /// <summary>English: Unrecognised</summary>
    public const string Format_Unknown = "Format_Unknown";

    /// <summary>English: SSH agents</summary>
    public const string Agents_Title = "Agents_Title";

    /// <summary>English: Endpoint</summary>
    public const string Agents_Endpoint = "Agents_Endpoint";

    /// <summary>English: Running</summary>
    public const string Agents_Running = "Agents_Running";

    /// <summary>English: Not running</summary>
    public const string Agents_Stopped = "Agents_Stopped";

    /// <summary>English: Locked</summary>
    public const string Agents_Locked = "Agents_Locked";

    /// <summary>English: Loaded keys</summary>
    public const string Agents_LoadedKeys = "Agents_LoadedKeys";

    /// <summary>English: This agent does not accept new keys</summary>
    public const string Agents_ReadOnly = "Agents_ReadOnly";

    /// <summary>English: Shell snippet</summary>
    public const string Agents_ShellSnippet = "Agents_ShellSnippet";

    /// <summary>English: No SSH agents found</summary>
    public const string Agents_Empty = "Agents_Empty";

    /// <summary>English: Algorithm</summary>
    public const string Agents_Column_Algorithm = "Agents_Column_Algorithm";

    /// <summary>English: Fingerprint</summary>
    public const string Agents_Column_Fingerprint = "Agents_Column_Fingerprint";

    /// <summary>English: Comment</summary>
    public const string Agents_Column_Comment = "Agents_Column_Comment";

    /// <summary>English: Remove from agent</summary>
    public const string Agents_RemoveKey = "Agents_RemoveKey";

    /// <summary>English: Remove all keys</summary>
    public const string Agents_RemoveAll = "Agents_RemoveAll";

    /// <summary>English: Click again to remove every key</summary>
    public const string Agents_RemoveAllConfirm = "Agents_RemoveAllConfirm";

    /// <summary>English: Lock</summary>
    public const string Agents_Lock = "Agents_Lock";

    /// <summary>English: Unlock</summary>
    public const string Agents_Unlock = "Agents_Unlock";

    /// <summary>English: Load a key…</summary>
    public const string Agents_AddKey = "Agents_AddKey";

    /// <summary>English: That key is passphrase protected. Load it with ssh-add from a terminal; GitVault will not carry your passphrase into another program.</summary>
    public const string Agents_AddKey_NeedsPassphrase = "Agents_AddKey_NeedsPassphrase";

    /// <summary>English: Copy snippet</summary>
    public const string Agents_CopySnippet = "Agents_CopySnippet";

    /// <summary>English: Shell</summary>
    public const string Agents_Shell = "Agents_Shell";

    /// <summary>English: OpenSSH agent</summary>
    public const string AgentKind_OpenSshUnix = "AgentKind_OpenSshUnix";

    /// <summary>English: OpenSSH agent (Windows service)</summary>
    public const string AgentKind_OpenSshWindowsPipe = "AgentKind_OpenSshWindowsPipe";

    /// <summary>English: Pageant</summary>
    public const string AgentKind_Pageant = "AgentKind_Pageant";

    /// <summary>English: gpg-agent</summary>
    public const string AgentKind_GpgAgent = "AgentKind_GpgAgent";

    /// <summary>English: 1Password</summary>
    public const string AgentKind_OnePassword = "AgentKind_OnePassword";

    /// <summary>English: KeeAgent</summary>
    public const string AgentKind_KeeAgent = "AgentKind_KeeAgent";

    /// <summary>English: WSL relay</summary>
    public const string AgentKind_WslRelay = "AgentKind_WslRelay";

    /// <summary>English: Unrecognised agent</summary>
    public const string AgentKind_Unknown = "AgentKind_Unknown";

    /// <summary>English: Credentials</summary>
    public const string Credentials_Title = "Credentials_Title";

    /// <summary>English: Host</summary>
    public const string Credentials_Column_Host = "Credentials_Column_Host";

    /// <summary>English: User name</summary>
    public const string Credentials_Column_UserName = "Credentials_Column_UserName";

    /// <summary>English: Protocol</summary>
    public const string Credentials_Column_Protocol = "Credentials_Column_Protocol";

    /// <summary>English: Store</summary>
    public const string Credentials_Column_Vault = "Credentials_Column_Vault";

    /// <summary>English: Owning client</summary>
    public const string Credentials_Column_Client = "Credentials_Column_Client";

    /// <summary>English: Last written</summary>
    public const string Credentials_Column_LastWrite = "Credentials_Column_LastWrite";

    /// <summary>English: Reveal secret</summary>
    public const string Credentials_Reveal = "Credentials_Reveal";

    /// <summary>English: No credentials found</summary>
    public const string Credentials_Empty = "Credentials_Empty";

    /// <summary>English: Target</summary>
    public const string Credentials_Column_Target = "Credentials_Column_Target";

    /// <summary>English: Show entries unrelated to Git</summary>
    public const string Credentials_ShowAll = "Credentials_ShowAll";

    /// <summary>English: Click again to show the secret on screen</summary>
    public const string Credentials_RevealConfirm = "Credentials_RevealConfirm";

    /// <summary>English: Hide</summary>
    public const string Credentials_Hide = "Credentials_Hide";

    /// <summary>English: Copy secret</summary>
    public const string Credentials_CopySecret = "Credentials_CopySecret";

    /// <summary>English: Hiding in {0} s</summary>
    public const string Credentials_HidingIn = "Credentials_HidingIn";

    /// <summary>English: The clipboard is cleared afterwards, but a clipboard manager may keep its own copy.</summary>
    public const string Credentials_ClipboardNote = "Credentials_ClipboardNote";

    /// <summary>English: Stored in plain text</summary>
    public const string Credentials_PlaintextBadge = "Credentials_PlaintextBadge";

    /// <summary>English: Test with git credential fill</summary>
    public const string Credentials_TestWithGit = "Credentials_TestWithGit";

    /// <summary>English: Windows Credential Manager</summary>
    public const string Vault_WindowsCredentialManager = "Vault_WindowsCredentialManager";

    /// <summary>English: Keychain</summary>
    public const string Vault_MacKeychain = "Vault_MacKeychain";

    /// <summary>English: Secret Service</summary>
    public const string Vault_SecretService = "Vault_SecretService";

    /// <summary>English: KWallet</summary>
    public const string Vault_KWallet = "Vault_KWallet";

    /// <summary>English: git-credentials file</summary>
    public const string Vault_GitCredentialsFile = "Vault_GitCredentialsFile";

    /// <summary>English: GCM plaintext store</summary>
    public const string Vault_GcmPlaintext = "Vault_GcmPlaintext";

    /// <summary>English: GCM DPAPI store</summary>
    public const string Vault_GcmDpapi = "Vault_GcmDpapi";

    /// <summary>English: GCM GPG store</summary>
    public const string Vault_GcmGpg = "Vault_GcmGpg";

    /// <summary>English: GitKraken secure box</summary>
    public const string Vault_GitKrakenBox = "Vault_GitKrakenBox";

    /// <summary>English: git credential cache</summary>
    public const string Vault_GitCredentialCache = "Vault_GitCredentialCache";

    /// <summary>English: Unrecognised store</summary>
    public const string Vault_Unknown = "Vault_Unknown";

    /// <summary>English: Git clients</summary>
    public const string Clients_Title = "Clients_Title";

    /// <summary>English: Version</summary>
    public const string Clients_Version = "Clients_Version";

    /// <summary>English: Install path</summary>
    public const string Clients_InstallPath = "Clients_InstallPath";

    /// <summary>English: Configuration folders</summary>
    public const string Clients_ConfigRoots = "Clients_ConfigRoots";

    /// <summary>English: Detected, but its configuration could not be read</summary>
    public const string Clients_Opaque = "Clients_Opaque";

    /// <summary>English: No Git clients found</summary>
    public const string Clients_Empty = "Clients_Empty";

    /// <summary>English: Accounts</summary>
    public const string Clients_Accounts = "Clients_Accounts";

    /// <summary>English: Keys bound to remotes</summary>
    public const string Clients_BoundKeys = "Clients_BoundKeys";

    /// <summary>English: SSH program</summary>
    public const string Clients_SshCommand = "Clients_SshCommand";

    /// <summary>English: Open configuration folder</summary>
    public const string Clients_OpenConfigFolder = "Clients_OpenConfigFolder";

    /// <summary>English: Credential entries</summary>
    public const string Clients_CredentialsCount = "Clients_CredentialsCount";

    /// <summary>English: A remote points at a key file that is gone</summary>
    public const string Warning_TortoiseGitMissingKey_Title = "Warning_TortoiseGitMissingKey_Title";

    /// <summary>English: TortoiseGit has a remote bound to a PuTTY key that no longer exists on disk, so pushing to it will fail. Rebind the remote to a key you still have, or restore the file.</summary>
    public const string Warning_TortoiseGitMissingKey_Body = "Warning_TortoiseGitMissingKey_Body";

    /// <summary>English: A WSL distribution has its own SSH keys</summary>
    public const string Warning_WslSeparateKeys_Title = "Warning_WslSeparateKeys_Title";

    /// <summary>English: Keys inside a WSL distribution are a separate set from the ones in your Windows home directory. Work done inside the distribution uses these, which is easy to forget when a push suddenly stops working on one side.</summary>
    public const string Warning_WslSeparateKeys_Body = "Warning_WslSeparateKeys_Body";

    /// <summary>English: Profiles</summary>
    public const string Profiles_Title = "Profiles_Title";

    /// <summary>English: Activate</summary>
    public const string Profiles_Activate_Button = "Profiles_Activate_Button";

    /// <summary>English: Deactivate</summary>
    public const string Profiles_Deactivate_Button = "Profiles_Deactivate_Button";

    /// <summary>English: Global (this user)</summary>
    public const string Profiles_Scope_Global = "Profiles_Scope_Global";

    /// <summary>English: System (all users)</summary>
    public const string Profiles_Scope_System = "Profiles_Scope_System";

    /// <summary>English: This repository</summary>
    public const string Profiles_Scope_Repository = "Profiles_Scope_Repository";

    /// <summary>English: Dry run — show changes without applying them</summary>
    public const string Profiles_DryRun = "Profiles_DryRun";

    /// <summary>English: Roll back</summary>
    public const string Profiles_Rollback = "Profiles_Rollback";

    /// <summary>English: Recent activations</summary>
    public const string Profiles_RecentActivations = "Profiles_RecentActivations";

    /// <summary>English: No profiles yet</summary>
    public const string Profiles_Empty = "Profiles_Empty";

    /// <summary>English: Preview changes</summary>
    public const string Profiles_Preview = "Profiles_Preview";

    /// <summary>English: Planned changes</summary>
    public const string Profiles_PlannedChanges = "Profiles_PlannedChanges";

    /// <summary>English: Everything is already as this profile wants it.</summary>
    public const string Profiles_NothingToDo = "Profiles_NothingToDo";

    /// <summary>English: Preview the changes before applying them.</summary>
    public const string Profiles_ApplyDryRunFirst = "Profiles_ApplyDryRunFirst";

    /// <summary>English: Applied. A snapshot was taken first, so this can be rolled back.</summary>
    public const string Profiles_Applied = "Profiles_Applied";

    /// <summary>English: This cannot be applied yet</summary>
    public const string Profiles_Blocked = "Profiles_Blocked";

    /// <summary>English: This cannot be applied yet: {0}</summary>
    public const string Profiles_BlockedWithReasons = "Profiles_BlockedWithReasons";

    /// <summary>English: Profile</summary>
    public const string Profiles_Column_Name = "Profiles_Column_Name";

    /// <summary>English: Identity</summary>
    public const string Profiles_Column_Identity = "Profiles_Column_Identity";

    /// <summary>English: Credential helper</summary>
    public const string Profiles_Column_Helper = "Profiles_Column_Helper";

    /// <summary>English: Active here</summary>
    public const string Profiles_IsActive = "Profiles_IsActive";

    /// <summary>English: Scan for repositories</summary>
    public const string Repositories_Scan = "Repositories_Scan";

    /// <summary>English: Scanning…</summary>
    public const string Repositories_Scanning = "Repositories_Scanning";

    /// <summary>English: Add a folder in Settings to search for repositories.</summary>
    public const string Repositories_NoRoots = "Repositories_NoRoots";

    /// <summary>English: Repository</summary>
    public const string Repositories_Column_Name = "Repositories_Column_Name";

    /// <summary>English: {0} &lt;{1}&gt;</summary>
    public const string Identities_NameAndEmail = "Identities_NameAndEmail";

    /// <summary>English: Repositories</summary>
    public const string Repositories_Title = "Repositories_Title";

    /// <summary>English: Add folder…</summary>
    public const string Repositories_AddRoot = "Repositories_AddRoot";

    /// <summary>English: Path</summary>
    public const string Repositories_Column_Path = "Repositories_Column_Path";

    /// <summary>English: Effective identity</summary>
    public const string Repositories_Column_EffectiveIdentity = "Repositories_Column_EffectiveIdentity";

    /// <summary>English: Remote</summary>
    public const string Repositories_Column_Remote = "Repositories_Column_Remote";

    /// <summary>English: No repositories found</summary>
    public const string Repositories_Empty = "Repositories_Empty";

    /// <summary>English: Settings</summary>
    public const string Settings_Title = "Settings_Title";

    /// <summary>English: Language</summary>
    public const string Settings_Language = "Settings_Language";

    /// <summary>English: Theme</summary>
    public const string Settings_Theme = "Settings_Theme";

    /// <summary>English: Follow system</summary>
    public const string Settings_Theme_System = "Settings_Theme_System";

    /// <summary>English: Light</summary>
    public const string Settings_Theme_Light = "Settings_Theme_Light";

    /// <summary>English: Dark</summary>
    public const string Settings_Theme_Dark = "Settings_Theme_Dark";

    /// <summary>English: Dry run by default</summary>
    public const string Settings_DryRunDefault = "Settings_DryRunDefault";

    /// <summary>English: Rescan when files change</summary>
    public const string Settings_WatchForChanges = "Settings_WatchForChanges";

    /// <summary>English: Log level</summary>
    public const string Settings_LogLevel = "Settings_LogLevel";

    /// <summary>English: Open logs folder</summary>
    public const string Settings_OpenLogsFolder = "Settings_OpenLogsFolder";

    /// <summary>English: Repository scan folders</summary>
    public const string Settings_ScanRoots = "Settings_ScanRoots";

    /// <summary>English: Extra key folders</summary>
    public const string Settings_CustomKeyFolders = "Settings_CustomKeyFolders";

    /// <summary>English: Secret reveal policy</summary>
    public const string Settings_RevealPolicy = "Settings_RevealPolicy";

    /// <summary>English: Hide a revealed secret after {0} s</summary>
    public const string Settings_AutoHideSeconds = "Settings_AutoHideSeconds";

    /// <summary>English: Clear the clipboard after {0} s</summary>
    public const string Settings_ClipboardClearSeconds = "Settings_ClipboardClearSeconds";

    /// <summary>English: Diagnostics</summary>
    public const string Settings_Diagnostics = "Settings_Diagnostics";

    /// <summary>English: Preview diagnostics bundle</summary>
    public const string Settings_PreviewDiagnostics = "Settings_PreviewDiagnostics";

    /// <summary>English: Save bundle…</summary>
    public const string Settings_SaveDiagnostics = "Settings_SaveDiagnostics";

    /// <summary>English: Nothing is written until you have seen exactly what the bundle contains. Values from your Git configuration are never included, only the names of the settings.</summary>
    public const string Settings_DiagnosticsNote = "Settings_DiagnosticsNote";

    /// <summary>English: Saved to {0}</summary>
    public const string Settings_DiagnosticsSaved = "Settings_DiagnosticsSaved";

    /// <summary>English: Telemetry</summary>
    public const string Settings_Telemetry = "Settings_Telemetry";

    /// <summary>English: GitVault collects nothing and makes no network calls.</summary>
    public const string Settings_TelemetryNone = "Settings_TelemetryNone";

    /// <summary>English: Logs</summary>
    public const string Logs_Title = "Logs_Title";

    /// <summary>English: Filter</summary>
    public const string Logs_Filter = "Logs_Filter";

    /// <summary>English: Clear view</summary>
    public const string Logs_Clear = "Logs_Clear";

    /// <summary>English: Time</summary>
    public const string Logs_Column_Timestamp = "Logs_Column_Timestamp";

    /// <summary>English: Level</summary>
    public const string Logs_Column_Level = "Logs_Column_Level";

    /// <summary>English: Message</summary>
    public const string Logs_Column_Message = "Logs_Column_Message";

    /// <summary>English: OK</summary>
    public const string Status_Ok = "Status_Ok";

    /// <summary>English: Not installed</summary>
    public const string Status_NotInstalled = "Status_NotInstalled";

    /// <summary>English: Access denied</summary>
    public const string Status_AccessDenied = "Status_AccessDenied";

    /// <summary>English: Timed out</summary>
    public const string Status_Timeout = "Status_Timeout";

    /// <summary>English: Could not be parsed</summary>
    public const string Status_ParseError = "Status_ParseError";

    /// <summary>English: Not applicable here</summary>
    public const string Status_NotApplicable = "Status_NotApplicable";

    /// <summary>English: Failed</summary>
    public const string Status_Failed = "Status_Failed";

    /// <summary>English: Private key is readable by others</summary>
    public const string Warning_KeyWorldReadable_Title = "Warning_KeyWorldReadable_Title";

    /// <summary>English: OpenSSH refuses to use a private key that other accounts on this machine can read. Set the file mode to 0600 so that only you can read it.</summary>
    public const string Warning_KeyWorldReadable_Body = "Warning_KeyWorldReadable_Body";

    /// <summary>English: RSA key is shorter than 3072 bits</summary>
    public const string Warning_RsaTooShort_Title = "Warning_RsaTooShort_Title";

    /// <summary>English: Short RSA keys no longer meet current guidance. Generate a new Ed25519 key, or an RSA key of at least 3072 bits, and replace this one on every host that trusts it.</summary>
    public const string Warning_RsaTooShort_Body = "Warning_RsaTooShort_Body";

    /// <summary>English: DSA key found</summary>
    public const string Warning_DsaDeprecated_Title = "Warning_DsaDeprecated_Title";

    /// <summary>English: DSA is disabled by default in current OpenSSH releases and will stop working. Replace it with an Ed25519 key.</summary>
    public const string Warning_DsaDeprecated_Body = "Warning_DsaDeprecated_Body";

    /// <summary>English: Private key has no passphrase</summary>
    public const string Warning_KeyNoPassphrase_Title = "Warning_KeyNoPassphrase_Title";

    /// <summary>English: Anyone who copies this file gets your access. Add a passphrase and load the key into an agent so you still type it only once per session.</summary>
    public const string Warning_KeyNoPassphrase_Body = "Warning_KeyNoPassphrase_Body";

    /// <summary>English: Public key without a private key</summary>
    public const string Warning_OrphanedPublicKey_Title = "Warning_OrphanedPublicKey_Title";

    /// <summary>English: A .pub file was found with no matching private key. Either the private key lives elsewhere, or it is held only by a hardware token or an agent.</summary>
    public const string Warning_OrphanedPublicKey_Body = "Warning_OrphanedPublicKey_Body";

    /// <summary>English: Credentials stored in plain text</summary>
    public const string Warning_PlaintextCredentialStore_Title = "Warning_PlaintextCredentialStore_Title";

    /// <summary>English: This store keeps passwords and tokens unencrypted on disk. Switch the credential helper to your operating system&apos;s vault.</summary>
    public const string Warning_PlaintextCredentialStore_Body = "Warning_PlaintextCredentialStore_Body";

    /// <summary>English: No .pub file next to the private key</summary>
    public const string Warning_MissingPublicKey_Title = "Warning_MissingPublicKey_Title";

    /// <summary>English: Several tools expect the public key to sit beside the private one. GitVault can write it: for an unencrypted key it derives it directly, and for a protected key it asks for the passphrase first.</summary>
    public const string Warning_MissingPublicKey_Body = "Warning_MissingPublicKey_Body";

    /// <summary>English: The key file failed its own integrity check</summary>
    public const string Warning_KeyIntegrityFailed_Title = "Warning_KeyIntegrityFailed_Title";

    /// <summary>English: A PuTTY key file stores a MAC over its own contents, and this one does not match. The file has been edited or damaged since it was written; do not rely on it until you have checked where it came from.</summary>
    public const string Warning_KeyIntegrityFailed_Body = "Warning_KeyIntegrityFailed_Body";

    /// <summary>English: SSH agent is not running</summary>
    public const string Warning_AgentNotRunning_Title = "Warning_AgentNotRunning_Title";

    /// <summary>English: Keys cannot be held in memory while the agent is stopped, so you will be asked for the passphrase on every connection.</summary>
    public const string Warning_AgentNotRunning_Body = "Warning_AgentNotRunning_Body";

    /// <summary>English: No git executable found</summary>
    public const string Warning_GitNotFound_Title = "Warning_GitNotFound_Title";

    /// <summary>English: GitVault fell back to reading the configuration files itself. Conditional includes and platform path quirks are resolved less accurately than git would resolve them. Install git, or add it to PATH.</summary>
    public const string Warning_GitNotFound_Body = "Warning_GitNotFound_Body";

    /// <summary>English: No author identity configured</summary>
    public const string Warning_NoIdentityConfigured_Title = "Warning_NoIdentityConfigured_Title";

    /// <summary>English: Neither user.name nor user.email is set anywhere, so git will refuse to create a commit. Set them globally, or per repository through a profile.</summary>
    public const string Warning_NoIdentityConfigured_Body = "Warning_NoIdentityConfigured_Body";

    /// <summary>English: {0} key</summary>
    public const string Plural_Keys_One = "Plural_Keys_One";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Few = "Plural_Keys_Few";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Many = "Plural_Keys_Many";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Other = "Plural_Keys_Other";

    /// <summary>English: {0} identity</summary>
    public const string Plural_Identities_One = "Plural_Identities_One";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Few = "Plural_Identities_Few";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Many = "Plural_Identities_Many";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Other = "Plural_Identities_Other";

    /// <summary>English: {0} agent</summary>
    public const string Plural_Agents_One = "Plural_Agents_One";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Few = "Plural_Agents_Few";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Many = "Plural_Agents_Many";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Other = "Plural_Agents_Other";

    /// <summary>English: {0} credential</summary>
    public const string Plural_Credentials_One = "Plural_Credentials_One";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Few = "Plural_Credentials_Few";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Many = "Plural_Credentials_Many";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Other = "Plural_Credentials_Other";

    /// <summary>English: {0} client</summary>
    public const string Plural_Clients_One = "Plural_Clients_One";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Few = "Plural_Clients_Few";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Many = "Plural_Clients_Many";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Other = "Plural_Clients_Other";

    /// <summary>English: {0} warning</summary>
    public const string Plural_Warnings_One = "Plural_Warnings_One";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Few = "Plural_Warnings_Few";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Many = "Plural_Warnings_Many";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Other = "Plural_Warnings_Other";

    /// <summary>All keys, in declaration order.</summary>
    public static IReadOnlyList<string> All { get; } =
    [
        App_Title,
        App_Subtitle,
        App_WindowTitle,
        Nav_Dashboard,
        Nav_Identities,
        Nav_Keys,
        Nav_Agents,
        Nav_Credentials,
        Nav_Clients,
        Nav_Profiles,
        Nav_Repositories,
        Nav_Settings,
        Nav_Logs,
        Common_Rescan,
        Common_Search,
        Common_Cancel,
        Common_Ok,
        Common_Close,
        Common_Copy,
        Common_Apply,
        Common_Working,
        Common_NoData,
        Common_Details,
        Common_WhatDoesThisMean,
        Common_Yes,
        Common_No,
        Common_Never,
        Common_ListSeparator,
        Dashboard_Title,
        Dashboard_Subtitle,
        Dashboard_Card_Identities,
        Dashboard_Card_Keys,
        Dashboard_Card_Agents,
        Dashboard_Card_Credentials,
        Dashboard_Card_Clients,
        Dashboard_ActiveIdentity,
        Dashboard_NoScanYet,
        Dashboard_FixAllSafe,
        Dashboard_Warnings,
        Dashboard_ScanDuration,
        Dashboard_ProbeMatrix,
        Dashboard_Env_Os,
        Dashboard_Env_Cpu,
        Dashboard_Env_AppData,
        Dashboard_Env_Git,
        Dashboard_Env_GitPathAndVersion,
        Dashboard_Scanning,
        Identities_Title,
        Identities_Column_Name,
        Identities_Column_Email,
        Identities_Column_Source,
        Identities_Column_Hosts,
        Identities_Column_Scope,
        Identities_Column_Confidence,
        Identities_Column_SigningKey,
        Identities_Empty,
        Identities_Effective_Title,
        Identities_Effective_Key,
        Identities_Effective_Value,
        Identities_Effective_WinningScope,
        Identities_Effective_Unset,
        Identities_Effective_OverriddenIn,
        Identities_Detail_Occurrences,
        Scope_System,
        Scope_Global,
        Scope_Local,
        Scope_Worktree,
        Scope_Command,
        Scope_Unknown,
        Confidence_Certain,
        Confidence_Probable,
        Confidence_Heuristic,
        Source_GitSystemConfig,
        Source_GitGlobalConfig,
        Source_RepoLocal,
        Source_RepoWorktree,
        Source_GitIncludedFile,
        Source_Unknown,
        Keys_Title,
        Keys_Column_Algorithm,
        Keys_Column_Fingerprint,
        Keys_Column_Comment,
        Keys_Column_Path,
        Keys_Column_Format,
        Keys_Encrypted,
        Keys_NotEncrypted,
        Keys_InAgent,
        Keys_Empty,
        Keys_Column_Bits,
        Keys_Column_Protection,
        Keys_Detail_PublicKey,
        Keys_Detail_Permissions,
        Keys_Detail_KdfRounds,
        Keys_Hardware,
        Keys_CopyPublicKey,
        Keys_CopyFingerprint,
        Keys_RevealInFileManager,
        Keys_Copied,
        Format_OpenSsh,
        Format_Pem,
        Format_Pkcs8,
        Format_Ppk2,
        Format_Ppk3,
        Format_PublicOnly,
        Format_Unknown,
        Agents_Title,
        Agents_Endpoint,
        Agents_Running,
        Agents_Stopped,
        Agents_Locked,
        Agents_LoadedKeys,
        Agents_ReadOnly,
        Agents_ShellSnippet,
        Agents_Empty,
        Agents_Column_Algorithm,
        Agents_Column_Fingerprint,
        Agents_Column_Comment,
        Agents_RemoveKey,
        Agents_RemoveAll,
        Agents_RemoveAllConfirm,
        Agents_Lock,
        Agents_Unlock,
        Agents_AddKey,
        Agents_AddKey_NeedsPassphrase,
        Agents_CopySnippet,
        Agents_Shell,
        AgentKind_OpenSshUnix,
        AgentKind_OpenSshWindowsPipe,
        AgentKind_Pageant,
        AgentKind_GpgAgent,
        AgentKind_OnePassword,
        AgentKind_KeeAgent,
        AgentKind_WslRelay,
        AgentKind_Unknown,
        Credentials_Title,
        Credentials_Column_Host,
        Credentials_Column_UserName,
        Credentials_Column_Protocol,
        Credentials_Column_Vault,
        Credentials_Column_Client,
        Credentials_Column_LastWrite,
        Credentials_Reveal,
        Credentials_Empty,
        Credentials_Column_Target,
        Credentials_ShowAll,
        Credentials_RevealConfirm,
        Credentials_Hide,
        Credentials_CopySecret,
        Credentials_HidingIn,
        Credentials_ClipboardNote,
        Credentials_PlaintextBadge,
        Credentials_TestWithGit,
        Vault_WindowsCredentialManager,
        Vault_MacKeychain,
        Vault_SecretService,
        Vault_KWallet,
        Vault_GitCredentialsFile,
        Vault_GcmPlaintext,
        Vault_GcmDpapi,
        Vault_GcmGpg,
        Vault_GitKrakenBox,
        Vault_GitCredentialCache,
        Vault_Unknown,
        Clients_Title,
        Clients_Version,
        Clients_InstallPath,
        Clients_ConfigRoots,
        Clients_Opaque,
        Clients_Empty,
        Clients_Accounts,
        Clients_BoundKeys,
        Clients_SshCommand,
        Clients_OpenConfigFolder,
        Clients_CredentialsCount,
        Warning_TortoiseGitMissingKey_Title,
        Warning_TortoiseGitMissingKey_Body,
        Warning_WslSeparateKeys_Title,
        Warning_WslSeparateKeys_Body,
        Profiles_Title,
        Profiles_Activate_Button,
        Profiles_Deactivate_Button,
        Profiles_Scope_Global,
        Profiles_Scope_System,
        Profiles_Scope_Repository,
        Profiles_DryRun,
        Profiles_Rollback,
        Profiles_RecentActivations,
        Profiles_Empty,
        Profiles_Preview,
        Profiles_PlannedChanges,
        Profiles_NothingToDo,
        Profiles_ApplyDryRunFirst,
        Profiles_Applied,
        Profiles_Blocked,
        Profiles_BlockedWithReasons,
        Profiles_Column_Name,
        Profiles_Column_Identity,
        Profiles_Column_Helper,
        Profiles_IsActive,
        Repositories_Scan,
        Repositories_Scanning,
        Repositories_NoRoots,
        Repositories_Column_Name,
        Identities_NameAndEmail,
        Repositories_Title,
        Repositories_AddRoot,
        Repositories_Column_Path,
        Repositories_Column_EffectiveIdentity,
        Repositories_Column_Remote,
        Repositories_Empty,
        Settings_Title,
        Settings_Language,
        Settings_Theme,
        Settings_Theme_System,
        Settings_Theme_Light,
        Settings_Theme_Dark,
        Settings_DryRunDefault,
        Settings_WatchForChanges,
        Settings_LogLevel,
        Settings_OpenLogsFolder,
        Settings_ScanRoots,
        Settings_CustomKeyFolders,
        Settings_RevealPolicy,
        Settings_AutoHideSeconds,
        Settings_ClipboardClearSeconds,
        Settings_Diagnostics,
        Settings_PreviewDiagnostics,
        Settings_SaveDiagnostics,
        Settings_DiagnosticsNote,
        Settings_DiagnosticsSaved,
        Settings_Telemetry,
        Settings_TelemetryNone,
        Logs_Title,
        Logs_Filter,
        Logs_Clear,
        Logs_Column_Timestamp,
        Logs_Column_Level,
        Logs_Column_Message,
        Status_Ok,
        Status_NotInstalled,
        Status_AccessDenied,
        Status_Timeout,
        Status_ParseError,
        Status_NotApplicable,
        Status_Failed,
        Warning_KeyWorldReadable_Title,
        Warning_KeyWorldReadable_Body,
        Warning_RsaTooShort_Title,
        Warning_RsaTooShort_Body,
        Warning_DsaDeprecated_Title,
        Warning_DsaDeprecated_Body,
        Warning_KeyNoPassphrase_Title,
        Warning_KeyNoPassphrase_Body,
        Warning_OrphanedPublicKey_Title,
        Warning_OrphanedPublicKey_Body,
        Warning_PlaintextCredentialStore_Title,
        Warning_PlaintextCredentialStore_Body,
        Warning_MissingPublicKey_Title,
        Warning_MissingPublicKey_Body,
        Warning_KeyIntegrityFailed_Title,
        Warning_KeyIntegrityFailed_Body,
        Warning_AgentNotRunning_Title,
        Warning_AgentNotRunning_Body,
        Warning_GitNotFound_Title,
        Warning_GitNotFound_Body,
        Warning_NoIdentityConfigured_Title,
        Warning_NoIdentityConfigured_Body,
        Plural_Keys_One,
        Plural_Keys_Few,
        Plural_Keys_Many,
        Plural_Keys_Other,
        Plural_Identities_One,
        Plural_Identities_Few,
        Plural_Identities_Many,
        Plural_Identities_Other,
        Plural_Agents_One,
        Plural_Agents_Few,
        Plural_Agents_Many,
        Plural_Agents_Other,
        Plural_Credentials_One,
        Plural_Credentials_Few,
        Plural_Credentials_Many,
        Plural_Credentials_Other,
        Plural_Clients_One,
        Plural_Clients_Few,
        Plural_Clients_Many,
        Plural_Clients_Other,
        Plural_Warnings_One,
        Plural_Warnings_Few,
        Plural_Warnings_Many,
        Plural_Warnings_Other,
    ];
}
