// <auto-generated />
// Generated from build/loc/strings.json by build/generate-localization.ps1. Do not edit.

namespace GitVault.Localization;

/// <summary>Every resource key defined by GitVault, as compile-time constants.</summary>
public static class Keys
{
    /// <summary>English: GitVault</summary>
    public const string App_Title = "App_Title";

    /// <summary>English: Git accounts, keys and credentials</summary>
    public const string App_Subtitle = "App_Subtitle";

    /// <summary>English: {0} — {1}</summary>
    public const string App_WindowTitle = "App_WindowTitle";

    /// <summary>English: Overview</summary>
    public const string Nav_Dashboard = "Nav_Dashboard";

    /// <summary>English: Identities</summary>
    public const string Nav_Identities = "Nav_Identities";

    /// <summary>English: SSH keys</summary>
    public const string Nav_Keys = "Nav_Keys";

    /// <summary>English: Agents</summary>
    public const string Nav_Agents = "Nav_Agents";

    /// <summary>English: Credentials</summary>
    public const string Nav_Credentials = "Nav_Credentials";

    /// <summary>English: Clients</summary>
    public const string Nav_Clients = "Nav_Clients";

    /// <summary>English: Profiles</summary>
    public const string Nav_Profiles = "Nav_Profiles";

    /// <summary>English: Repositories</summary>
    public const string Nav_Repositories = "Nav_Repositories";

    /// <summary>English: Options</summary>
    public const string Nav_Settings = "Nav_Settings";

    /// <summary>English: Logs</summary>
    public const string Nav_Logs = "Nav_Logs";

    /// <summary>English: Rescan</summary>
    public const string Common_Rescan = "Common_Rescan";

    /// <summary>English: Search</summary>
    public const string Common_Search = "Common_Search";

    /// <summary>English: Cancel</summary>
    public const string Common_Cancel = "Common_Cancel";

    /// <summary>English: OK</summary>
    public const string Common_Ok = "Common_Ok";

    /// <summary>English: Close</summary>
    public const string Common_Close = "Common_Close";

    /// <summary>English: Copy</summary>
    public const string Common_Copy = "Common_Copy";

    /// <summary>English: Apply</summary>
    public const string Common_Apply = "Common_Apply";

    /// <summary>English: Working…</summary>
    public const string Common_Working = "Common_Working";

    /// <summary>English: Nothing to show</summary>
    public const string Common_NoData = "Common_NoData";

    /// <summary>English: Details</summary>
    public const string Common_Details = "Common_Details";

    /// <summary>English: What does this mean?</summary>
    public const string Common_WhatDoesThisMean = "Common_WhatDoesThisMean";

    /// <summary>English: Yes</summary>
    public const string Common_Yes = "Common_Yes";

    /// <summary>English: No</summary>
    public const string Common_No = "Common_No";

    /// <summary>English: Never</summary>
    public const string Common_Never = "Common_Never";

    /// <summary>English: , </summary>
    public const string Common_ListSeparator = "Common_ListSeparator";

    /// <summary>English: Overview</summary>
    public const string Dashboard_Title = "Dashboard_Title";

    /// <summary>English: Identity and Git configuration status for this computer.</summary>
    public const string Dashboard_Subtitle = "Dashboard_Subtitle";

    /// <summary>English: Identities</summary>
    public const string Dashboard_Card_Identities = "Dashboard_Card_Identities";

    /// <summary>English: SSH keys</summary>
    public const string Dashboard_Card_Keys = "Dashboard_Card_Keys";

    /// <summary>English: Agents</summary>
    public const string Dashboard_Card_Agents = "Dashboard_Card_Agents";

    /// <summary>English: Credentials</summary>
    public const string Dashboard_Card_Credentials = "Dashboard_Card_Credentials";

    /// <summary>English: Clients</summary>
    public const string Dashboard_Card_Clients = "Dashboard_Card_Clients";

    /// <summary>English: Active global identity</summary>
    public const string Dashboard_ActiveIdentity = "Dashboard_ActiveIdentity";

    /// <summary>English: No scan has run yet</summary>
    public const string Dashboard_NoScanYet = "Dashboard_NoScanYet";

    /// <summary>English: Fix all safe issues</summary>
    public const string Dashboard_FixAllSafe = "Dashboard_FixAllSafe";

    /// <summary>English: Health warnings</summary>
    public const string Dashboard_Warnings = "Dashboard_Warnings";

    /// <summary>English: Scan finished in {0} ms</summary>
    public const string Dashboard_ScanDuration = "Dashboard_ScanDuration";

    /// <summary>English: Probe status</summary>
    public const string Dashboard_ProbeMatrix = "Dashboard_ProbeMatrix";

    /// <summary>English: Operating system</summary>
    public const string Dashboard_Env_Os = "Dashboard_Env_Os";

    /// <summary>English: Architecture</summary>
    public const string Dashboard_Env_Cpu = "Dashboard_Env_Cpu";

    /// <summary>English: GitVault data folder</summary>
    public const string Dashboard_Env_AppData = "Dashboard_Env_AppData";

    /// <summary>English: Git executable</summary>
    public const string Dashboard_Env_Git = "Dashboard_Env_Git";

    /// <summary>English: {0} (version {1})</summary>
    public const string Dashboard_Env_GitPathAndVersion = "Dashboard_Env_GitPathAndVersion";

    /// <summary>English: Scanning…</summary>
    public const string Dashboard_Scanning = "Dashboard_Scanning";

    /// <summary>English: Identities</summary>
    public const string Identities_Title = "Identities_Title";

    /// <summary>English: Name</summary>
    public const string Identities_Column_Name = "Identities_Column_Name";

    /// <summary>English: E-mail</summary>
    public const string Identities_Column_Email = "Identities_Column_Email";

    /// <summary>English: Source</summary>
    public const string Identities_Column_Source = "Identities_Column_Source";

    /// <summary>English: Hosts</summary>
    public const string Identities_Column_Hosts = "Identities_Column_Hosts";

    /// <summary>English: Scope</summary>
    public const string Identities_Column_Scope = "Identities_Column_Scope";

    /// <summary>English: Confidence</summary>
    public const string Identities_Column_Confidence = "Identities_Column_Confidence";

    /// <summary>English: Signing key</summary>
    public const string Identities_Column_SigningKey = "Identities_Column_SigningKey";

    /// <summary>English: No identities found</summary>
    public const string Identities_Empty = "Identities_Empty";

    /// <summary>English: In effect for this user</summary>
    public const string Identities_Effective_Title = "Identities_Effective_Title";

    /// <summary>English: Setting</summary>
    public const string Identities_Effective_Key = "Identities_Effective_Key";

    /// <summary>English: Value</summary>
    public const string Identities_Effective_Value = "Identities_Effective_Value";

    /// <summary>English: Set in</summary>
    public const string Identities_Effective_WinningScope = "Identities_Effective_WinningScope";

    /// <summary>English: not set</summary>
    public const string Identities_Effective_Unset = "Identities_Effective_Unset";

    /// <summary>English: overrides {0}</summary>
    public const string Identities_Effective_OverriddenIn = "Identities_Effective_OverriddenIn";

    /// <summary>English: Seen in</summary>
    public const string Identities_Detail_Occurrences = "Identities_Detail_Occurrences";

    /// <summary>English: System</summary>
    public const string Scope_System = "Scope_System";

    /// <summary>English: Global</summary>
    public const string Scope_Global = "Scope_Global";

    /// <summary>English: Repository</summary>
    public const string Scope_Local = "Scope_Local";

    /// <summary>English: Worktree</summary>
    public const string Scope_Worktree = "Scope_Worktree";

    /// <summary>English: Command line</summary>
    public const string Scope_Command = "Scope_Command";

    /// <summary>English: Unknown</summary>
    public const string Scope_Unknown = "Scope_Unknown";

    /// <summary>English: Certain</summary>
    public const string Confidence_Certain = "Confidence_Certain";

    /// <summary>English: Probable</summary>
    public const string Confidence_Probable = "Confidence_Probable";

    /// <summary>English: Guessed</summary>
    public const string Confidence_Heuristic = "Confidence_Heuristic";

    /// <summary>English: System git config</summary>
    public const string Source_GitSystemConfig = "Source_GitSystemConfig";

    /// <summary>English: User git config</summary>
    public const string Source_GitGlobalConfig = "Source_GitGlobalConfig";

    /// <summary>English: Repository config</summary>
    public const string Source_RepoLocal = "Source_RepoLocal";

    /// <summary>English: Worktree config</summary>
    public const string Source_RepoWorktree = "Source_RepoWorktree";

    /// <summary>English: Included file</summary>
    public const string Source_GitIncludedFile = "Source_GitIncludedFile";

    /// <summary>English: Unknown source</summary>
    public const string Source_Unknown = "Source_Unknown";

    /// <summary>English: SSH keys</summary>
    public const string Keys_Title = "Keys_Title";

    /// <summary>English: Algorithm</summary>
    public const string Keys_Column_Algorithm = "Keys_Column_Algorithm";

    /// <summary>English: Fingerprint</summary>
    public const string Keys_Column_Fingerprint = "Keys_Column_Fingerprint";

    /// <summary>English: Comment</summary>
    public const string Keys_Column_Comment = "Keys_Column_Comment";

    /// <summary>English: Path</summary>
    public const string Keys_Column_Path = "Keys_Column_Path";

    /// <summary>English: Format</summary>
    public const string Keys_Column_Format = "Keys_Column_Format";

    /// <summary>English: Passphrase protected</summary>
    public const string Keys_Encrypted = "Keys_Encrypted";

    /// <summary>English: No passphrase</summary>
    public const string Keys_NotEncrypted = "Keys_NotEncrypted";

    /// <summary>English: Loaded in agent</summary>
    public const string Keys_InAgent = "Keys_InAgent";

    /// <summary>English: No SSH keys found</summary>
    public const string Keys_Empty = "Keys_Empty";

    /// <summary>English: Bits</summary>
    public const string Keys_Column_Bits = "Keys_Column_Bits";

    /// <summary>English: Protection</summary>
    public const string Keys_Column_Protection = "Keys_Column_Protection";

    /// <summary>English: Public key</summary>
    public const string Keys_Detail_PublicKey = "Keys_Detail_PublicKey";

    /// <summary>English: File mode</summary>
    public const string Keys_Detail_Permissions = "Keys_Detail_Permissions";

    /// <summary>English: KDF rounds</summary>
    public const string Keys_Detail_KdfRounds = "Keys_Detail_KdfRounds";

    /// <summary>English: Hardware-backed</summary>
    public const string Keys_Hardware = "Keys_Hardware";

    /// <summary>English: Copy public key</summary>
    public const string Keys_CopyPublicKey = "Keys_CopyPublicKey";

    /// <summary>English: Copy fingerprint</summary>
    public const string Keys_CopyFingerprint = "Keys_CopyFingerprint";

    /// <summary>English: Show in file manager</summary>
    public const string Keys_RevealInFileManager = "Keys_RevealInFileManager";

    /// <summary>English: Copied to the clipboard</summary>
    public const string Keys_Copied = "Keys_Copied";

    /// <summary>English: OpenSSH</summary>
    public const string Format_OpenSsh = "Format_OpenSsh";

    /// <summary>English: PEM</summary>
    public const string Format_Pem = "Format_Pem";

    /// <summary>English: PKCS#8</summary>
    public const string Format_Pkcs8 = "Format_Pkcs8";

    /// <summary>English: PuTTY v2</summary>
    public const string Format_Ppk2 = "Format_Ppk2";

    /// <summary>English: PuTTY v3</summary>
    public const string Format_Ppk3 = "Format_Ppk3";

    /// <summary>English: Public key only</summary>
    public const string Format_PublicOnly = "Format_PublicOnly";

    /// <summary>English: Unrecognised</summary>
    public const string Format_Unknown = "Format_Unknown";

    /// <summary>English: SSH agents</summary>
    public const string Agents_Title = "Agents_Title";

    /// <summary>English: Endpoint</summary>
    public const string Agents_Endpoint = "Agents_Endpoint";

    /// <summary>English: Running</summary>
    public const string Agents_Running = "Agents_Running";

    /// <summary>English: Not running</summary>
    public const string Agents_Stopped = "Agents_Stopped";

    /// <summary>English: Locked</summary>
    public const string Agents_Locked = "Agents_Locked";

    /// <summary>English: Loaded keys</summary>
    public const string Agents_LoadedKeys = "Agents_LoadedKeys";

    /// <summary>English: This agent does not accept new keys</summary>
    public const string Agents_ReadOnly = "Agents_ReadOnly";

    /// <summary>English: Shell snippet</summary>
    public const string Agents_ShellSnippet = "Agents_ShellSnippet";

    /// <summary>English: No SSH agents found</summary>
    public const string Agents_Empty = "Agents_Empty";

    /// <summary>English: Algorithm</summary>
    public const string Agents_Column_Algorithm = "Agents_Column_Algorithm";

    /// <summary>English: Fingerprint</summary>
    public const string Agents_Column_Fingerprint = "Agents_Column_Fingerprint";

    /// <summary>English: Comment</summary>
    public const string Agents_Column_Comment = "Agents_Column_Comment";

    /// <summary>English: Remove from agent</summary>
    public const string Agents_RemoveKey = "Agents_RemoveKey";

    /// <summary>English: Remove all keys</summary>
    public const string Agents_RemoveAll = "Agents_RemoveAll";

    /// <summary>English: Click again to remove every key</summary>
    public const string Agents_RemoveAllConfirm = "Agents_RemoveAllConfirm";

    /// <summary>English: Lock</summary>
    public const string Agents_Lock = "Agents_Lock";

    /// <summary>English: Unlock</summary>
    public const string Agents_Unlock = "Agents_Unlock";

    /// <summary>English: Load a key…</summary>
    public const string Agents_AddKey = "Agents_AddKey";

    /// <summary>English: That key is passphrase protected. Load it with ssh-add from a terminal; GitVault will not carry your passphrase into another program.</summary>
    public const string Agents_AddKey_NeedsPassphrase = "Agents_AddKey_NeedsPassphrase";

    /// <summary>English: Copy snippet</summary>
    public const string Agents_CopySnippet = "Agents_CopySnippet";

    /// <summary>English: Shell</summary>
    public const string Agents_Shell = "Agents_Shell";

    /// <summary>English: OpenSSH agent</summary>
    public const string AgentKind_OpenSshUnix = "AgentKind_OpenSshUnix";

    /// <summary>English: OpenSSH agent (Windows service)</summary>
    public const string AgentKind_OpenSshWindowsPipe = "AgentKind_OpenSshWindowsPipe";

    /// <summary>English: Pageant</summary>
    public const string AgentKind_Pageant = "AgentKind_Pageant";

    /// <summary>English: gpg-agent</summary>
    public const string AgentKind_GpgAgent = "AgentKind_GpgAgent";

    /// <summary>English: 1Password</summary>
    public const string AgentKind_OnePassword = "AgentKind_OnePassword";

    /// <summary>English: KeeAgent</summary>
    public const string AgentKind_KeeAgent = "AgentKind_KeeAgent";

    /// <summary>English: WSL relay</summary>
    public const string AgentKind_WslRelay = "AgentKind_WslRelay";

    /// <summary>English: Unrecognised agent</summary>
    public const string AgentKind_Unknown = "AgentKind_Unknown";

    /// <summary>English: Credentials</summary>
    public const string Credentials_Title = "Credentials_Title";

    /// <summary>English: Host</summary>
    public const string Credentials_Column_Host = "Credentials_Column_Host";

    /// <summary>English: User name</summary>
    public const string Credentials_Column_UserName = "Credentials_Column_UserName";

    /// <summary>English: Protocol</summary>
    public const string Credentials_Column_Protocol = "Credentials_Column_Protocol";

    /// <summary>English: Store</summary>
    public const string Credentials_Column_Vault = "Credentials_Column_Vault";

    /// <summary>English: Owning client</summary>
    public const string Credentials_Column_Client = "Credentials_Column_Client";

    /// <summary>English: Last written</summary>
    public const string Credentials_Column_LastWrite = "Credentials_Column_LastWrite";

    /// <summary>English: Reveal secret</summary>
    public const string Credentials_Reveal = "Credentials_Reveal";

    /// <summary>English: No credentials found</summary>
    public const string Credentials_Empty = "Credentials_Empty";

    /// <summary>English: Target</summary>
    public const string Credentials_Column_Target = "Credentials_Column_Target";

    /// <summary>English: Show entries unrelated to Git</summary>
    public const string Credentials_ShowAll = "Credentials_ShowAll";

    /// <summary>English: Click again to show the secret on screen</summary>
    public const string Credentials_RevealConfirm = "Credentials_RevealConfirm";

    /// <summary>English: Hide</summary>
    public const string Credentials_Hide = "Credentials_Hide";

    /// <summary>English: Copy secret</summary>
    public const string Credentials_CopySecret = "Credentials_CopySecret";

    /// <summary>English: Hiding in {0} s</summary>
    public const string Credentials_HidingIn = "Credentials_HidingIn";

    /// <summary>English: The clipboard is cleared afterwards, but a clipboard manager may keep its own copy.</summary>
    public const string Credentials_ClipboardNote = "Credentials_ClipboardNote";

    /// <summary>English: Stored in plain text</summary>
    public const string Credentials_PlaintextBadge = "Credentials_PlaintextBadge";

    /// <summary>English: Test with git credential fill</summary>
    public const string Credentials_TestWithGit = "Credentials_TestWithGit";

    /// <summary>English: Windows Credential Manager</summary>
    public const string Vault_WindowsCredentialManager = "Vault_WindowsCredentialManager";

    /// <summary>English: Keychain</summary>
    public const string Vault_MacKeychain = "Vault_MacKeychain";

    /// <summary>English: Secret Service</summary>
    public const string Vault_SecretService = "Vault_SecretService";

    /// <summary>English: KWallet</summary>
    public const string Vault_KWallet = "Vault_KWallet";

    /// <summary>English: git-credentials file</summary>
    public const string Vault_GitCredentialsFile = "Vault_GitCredentialsFile";

    /// <summary>English: GCM plaintext store</summary>
    public const string Vault_GcmPlaintext = "Vault_GcmPlaintext";

    /// <summary>English: GCM DPAPI store</summary>
    public const string Vault_GcmDpapi = "Vault_GcmDpapi";

    /// <summary>English: GCM GPG store</summary>
    public const string Vault_GcmGpg = "Vault_GcmGpg";

    /// <summary>English: GitKraken secure box</summary>
    public const string Vault_GitKrakenBox = "Vault_GitKrakenBox";

    /// <summary>English: git credential cache</summary>
    public const string Vault_GitCredentialCache = "Vault_GitCredentialCache";

    /// <summary>English: Unrecognised store</summary>
    public const string Vault_Unknown = "Vault_Unknown";

    /// <summary>English: Git clients</summary>
    public const string Clients_Title = "Clients_Title";

    /// <summary>English: Version</summary>
    public const string Clients_Version = "Clients_Version";

    /// <summary>English: Install path</summary>
    public const string Clients_InstallPath = "Clients_InstallPath";

    /// <summary>English: Configuration folders</summary>
    public const string Clients_ConfigRoots = "Clients_ConfigRoots";

    /// <summary>English: Detected, but its configuration could not be read</summary>
    public const string Clients_Opaque = "Clients_Opaque";

    /// <summary>English: No Git clients found</summary>
    public const string Clients_Empty = "Clients_Empty";

    /// <summary>English: Accounts</summary>
    public const string Clients_Accounts = "Clients_Accounts";

    /// <summary>English: Keys bound to remotes</summary>
    public const string Clients_BoundKeys = "Clients_BoundKeys";

    /// <summary>English: SSH program</summary>
    public const string Clients_SshCommand = "Clients_SshCommand";

    /// <summary>English: Open configuration folder</summary>
    public const string Clients_OpenConfigFolder = "Clients_OpenConfigFolder";

    /// <summary>English: Credential entries</summary>
    public const string Clients_CredentialsCount = "Clients_CredentialsCount";

    /// <summary>English: A remote points at a key file that is gone</summary>
    public const string Warning_TortoiseGitMissingKey_Title = "Warning_TortoiseGitMissingKey_Title";

    /// <summary>English: TortoiseGit has a remote bound to a PuTTY key that no longer exists on disk, so pushing to it will fail. Rebind the remote to a key you still have, or restore the file.</summary>
    public const string Warning_TortoiseGitMissingKey_Body = "Warning_TortoiseGitMissingKey_Body";

    /// <summary>English: A WSL distribution has its own SSH keys</summary>
    public const string Warning_WslSeparateKeys_Title = "Warning_WslSeparateKeys_Title";

    /// <summary>English: Keys inside a WSL distribution are a separate set from the ones in your Windows home directory. Work done inside the distribution uses these, which is easy to forget when a push suddenly stops working on one side.</summary>
    public const string Warning_WslSeparateKeys_Body = "Warning_WslSeparateKeys_Body";

    /// <summary>English: Profiles</summary>
    public const string Profiles_Title = "Profiles_Title";

    /// <summary>English: Activate</summary>
    public const string Profiles_Activate_Button = "Profiles_Activate_Button";

    /// <summary>English: Deactivate</summary>
    public const string Profiles_Deactivate_Button = "Profiles_Deactivate_Button";

    /// <summary>English: Global (this user)</summary>
    public const string Profiles_Scope_Global = "Profiles_Scope_Global";

    /// <summary>English: System (all users)</summary>
    public const string Profiles_Scope_System = "Profiles_Scope_System";

    /// <summary>English: This repository</summary>
    public const string Profiles_Scope_Repository = "Profiles_Scope_Repository";

    /// <summary>English: Dry run — show changes without applying them</summary>
    public const string Profiles_DryRun = "Profiles_DryRun";

    /// <summary>English: Roll back</summary>
    public const string Profiles_Rollback = "Profiles_Rollback";

    /// <summary>English: Recent activations</summary>
    public const string Profiles_RecentActivations = "Profiles_RecentActivations";

    /// <summary>English: No profiles yet</summary>
    public const string Profiles_Empty = "Profiles_Empty";

    /// <summary>English: Preview changes</summary>
    public const string Profiles_Preview = "Profiles_Preview";

    /// <summary>English: Planned changes</summary>
    public const string Profiles_PlannedChanges = "Profiles_PlannedChanges";

    /// <summary>English: Everything is already as this profile wants it.</summary>
    public const string Profiles_NothingToDo = "Profiles_NothingToDo";

    /// <summary>English: Preview the changes before applying them.</summary>
    public const string Profiles_ApplyDryRunFirst = "Profiles_ApplyDryRunFirst";

    /// <summary>English: Applied. A snapshot was taken first, so this can be rolled back.</summary>
    public const string Profiles_Applied = "Profiles_Applied";

    /// <summary>English: This cannot be applied yet</summary>
    public const string Profiles_Blocked = "Profiles_Blocked";

    /// <summary>English: This cannot be applied yet: {0}</summary>
    public const string Profiles_BlockedWithReasons = "Profiles_BlockedWithReasons";

    /// <summary>English: Profile</summary>
    public const string Profiles_Column_Name = "Profiles_Column_Name";

    /// <summary>English: Identity</summary>
    public const string Profiles_Column_Identity = "Profiles_Column_Identity";

    /// <summary>English: Credential helper</summary>
    public const string Profiles_Column_Helper = "Profiles_Column_Helper";

    /// <summary>English: Active here</summary>
    public const string Profiles_IsActive = "Profiles_IsActive";

    /// <summary>English: Scan for repositories</summary>
    public const string Repositories_Scan = "Repositories_Scan";

    /// <summary>English: Scanning…</summary>
    public const string Repositories_Scanning = "Repositories_Scanning";

    /// <summary>English: Add a folder in Settings to search for repositories.</summary>
    public const string Repositories_NoRoots = "Repositories_NoRoots";

    /// <summary>English: Repository</summary>
    public const string Repositories_Column_Name = "Repositories_Column_Name";

    /// <summary>English: {0} &lt;{1}&gt;</summary>
    public const string Identities_NameAndEmail = "Identities_NameAndEmail";

    /// <summary>English: Repositories</summary>
    public const string Repositories_Title = "Repositories_Title";

    /// <summary>English: Add folder…</summary>
    public const string Repositories_AddRoot = "Repositories_AddRoot";

    /// <summary>English: Path</summary>
    public const string Repositories_Column_Path = "Repositories_Column_Path";

    /// <summary>English: Effective identity</summary>
    public const string Repositories_Column_EffectiveIdentity = "Repositories_Column_EffectiveIdentity";

    /// <summary>English: Remote</summary>
    public const string Repositories_Column_Remote = "Repositories_Column_Remote";

    /// <summary>English: No repositories found</summary>
    public const string Repositories_Empty = "Repositories_Empty";

    /// <summary>English: Options</summary>
    public const string Settings_Title = "Settings_Title";

    /// <summary>English: Language</summary>
    public const string Settings_Language = "Settings_Language";

    /// <summary>English: Theme</summary>
    public const string Settings_Theme = "Settings_Theme";

    /// <summary>English: Follow system</summary>
    public const string Settings_Theme_System = "Settings_Theme_System";

    /// <summary>English: Light</summary>
    public const string Settings_Theme_Light = "Settings_Theme_Light";

    /// <summary>English: Dark</summary>
    public const string Settings_Theme_Dark = "Settings_Theme_Dark";

    /// <summary>English: Dry run by default</summary>
    public const string Settings_DryRunDefault = "Settings_DryRunDefault";

    /// <summary>English: Rescan when files change</summary>
    public const string Settings_WatchForChanges = "Settings_WatchForChanges";

    /// <summary>English: Log level</summary>
    public const string Settings_LogLevel = "Settings_LogLevel";

    /// <summary>English: Open logs folder</summary>
    public const string Settings_OpenLogsFolder = "Settings_OpenLogsFolder";

    /// <summary>English: Repository scan folders</summary>
    public const string Settings_ScanRoots = "Settings_ScanRoots";

    /// <summary>English: Extra key folders</summary>
    public const string Settings_CustomKeyFolders = "Settings_CustomKeyFolders";

    /// <summary>English: Secret reveal policy</summary>
    public const string Settings_RevealPolicy = "Settings_RevealPolicy";

    /// <summary>English: Hide a revealed secret after {0} s</summary>
    public const string Settings_AutoHideSeconds = "Settings_AutoHideSeconds";

    /// <summary>English: Clear the clipboard after {0} s</summary>
    public const string Settings_ClipboardClearSeconds = "Settings_ClipboardClearSeconds";

    /// <summary>English: Diagnostics</summary>
    public const string Settings_Diagnostics = "Settings_Diagnostics";

    /// <summary>English: Preview diagnostics bundle</summary>
    public const string Settings_PreviewDiagnostics = "Settings_PreviewDiagnostics";

    /// <summary>English: Save bundle…</summary>
    public const string Settings_SaveDiagnostics = "Settings_SaveDiagnostics";

    /// <summary>English: Nothing is written until you have seen exactly what the bundle contains. Values from your Git configuration are never included, only the names of the settings.</summary>
    public const string Settings_DiagnosticsNote = "Settings_DiagnosticsNote";

    /// <summary>English: Saved to {0}</summary>
    public const string Settings_DiagnosticsSaved = "Settings_DiagnosticsSaved";

    /// <summary>English: Telemetry</summary>
    public const string Settings_Telemetry = "Settings_Telemetry";

    /// <summary>English: GitVault collects nothing and makes no network calls.</summary>
    public const string Settings_TelemetryNone = "Settings_TelemetryNone";

    /// <summary>English: Logs</summary>
    public const string Logs_Title = "Logs_Title";

    /// <summary>English: Filter</summary>
    public const string Logs_Filter = "Logs_Filter";

    /// <summary>English: Clear view</summary>
    public const string Logs_Clear = "Logs_Clear";

    /// <summary>English: Time</summary>
    public const string Logs_Column_Timestamp = "Logs_Column_Timestamp";

    /// <summary>English: Level</summary>
    public const string Logs_Column_Level = "Logs_Column_Level";

    /// <summary>English: Message</summary>
    public const string Logs_Column_Message = "Logs_Column_Message";

    /// <summary>English: OK</summary>
    public const string Status_Ok = "Status_Ok";

    /// <summary>English: Not installed</summary>
    public const string Status_NotInstalled = "Status_NotInstalled";

    /// <summary>English: Access denied</summary>
    public const string Status_AccessDenied = "Status_AccessDenied";

    /// <summary>English: Timed out</summary>
    public const string Status_Timeout = "Status_Timeout";

    /// <summary>English: Could not be parsed</summary>
    public const string Status_ParseError = "Status_ParseError";

    /// <summary>English: Not applicable here</summary>
    public const string Status_NotApplicable = "Status_NotApplicable";

    /// <summary>English: Failed</summary>
    public const string Status_Failed = "Status_Failed";

    /// <summary>English: Private key is readable by others</summary>
    public const string Warning_KeyWorldReadable_Title = "Warning_KeyWorldReadable_Title";

    /// <summary>English: OpenSSH refuses to use a private key that other accounts on this machine can read. Set the file mode to 0600 so that only you can read it.</summary>
    public const string Warning_KeyWorldReadable_Body = "Warning_KeyWorldReadable_Body";

    /// <summary>English: RSA key is shorter than 3072 bits</summary>
    public const string Warning_RsaTooShort_Title = "Warning_RsaTooShort_Title";

    /// <summary>English: Short RSA keys no longer meet current guidance. Generate a new Ed25519 key, or an RSA key of at least 3072 bits, and replace this one on every host that trusts it.</summary>
    public const string Warning_RsaTooShort_Body = "Warning_RsaTooShort_Body";

    /// <summary>English: DSA key found</summary>
    public const string Warning_DsaDeprecated_Title = "Warning_DsaDeprecated_Title";

    /// <summary>English: DSA is disabled by default in current OpenSSH releases and will stop working. Replace it with an Ed25519 key.</summary>
    public const string Warning_DsaDeprecated_Body = "Warning_DsaDeprecated_Body";

    /// <summary>English: Private key has no passphrase</summary>
    public const string Warning_KeyNoPassphrase_Title = "Warning_KeyNoPassphrase_Title";

    /// <summary>English: Anyone who copies this file gets your access. Add a passphrase and load the key into an agent so you still type it only once per session.</summary>
    public const string Warning_KeyNoPassphrase_Body = "Warning_KeyNoPassphrase_Body";

    /// <summary>English: Public key without a private key</summary>
    public const string Warning_OrphanedPublicKey_Title = "Warning_OrphanedPublicKey_Title";

    /// <summary>English: A .pub file was found with no matching private key. Either the private key lives elsewhere, or it is held only by a hardware token or an agent.</summary>
    public const string Warning_OrphanedPublicKey_Body = "Warning_OrphanedPublicKey_Body";

    /// <summary>English: Credentials stored in plain text</summary>
    public const string Warning_PlaintextCredentialStore_Title = "Warning_PlaintextCredentialStore_Title";

    /// <summary>English: This store keeps passwords and tokens unencrypted on disk. Switch the credential helper to your operating system&apos;s vault.</summary>
    public const string Warning_PlaintextCredentialStore_Body = "Warning_PlaintextCredentialStore_Body";

    /// <summary>English: No .pub file next to the private key</summary>
    public const string Warning_MissingPublicKey_Title = "Warning_MissingPublicKey_Title";

    /// <summary>English: Several tools expect the public key to sit beside the private one. GitVault can write it: for an unencrypted key it derives it directly, and for a protected key it asks for the passphrase first.</summary>
    public const string Warning_MissingPublicKey_Body = "Warning_MissingPublicKey_Body";

    /// <summary>English: The key file failed its own integrity check</summary>
    public const string Warning_KeyIntegrityFailed_Title = "Warning_KeyIntegrityFailed_Title";

    /// <summary>English: A PuTTY key file stores a MAC over its own contents, and this one does not match. The file has been edited or damaged since it was written; do not rely on it until you have checked where it came from.</summary>
    public const string Warning_KeyIntegrityFailed_Body = "Warning_KeyIntegrityFailed_Body";

    /// <summary>English: SSH agent is not running</summary>
    public const string Warning_AgentNotRunning_Title = "Warning_AgentNotRunning_Title";

    /// <summary>English: Keys cannot be held in memory while the agent is stopped, so you will be asked for the passphrase on every connection.</summary>
    public const string Warning_AgentNotRunning_Body = "Warning_AgentNotRunning_Body";

    /// <summary>English: No git executable found</summary>
    public const string Warning_GitNotFound_Title = "Warning_GitNotFound_Title";

    /// <summary>English: GitVault fell back to reading the configuration files itself. Conditional includes and platform path quirks are resolved less accurately than git would resolve them. Install git, or add it to PATH.</summary>
    public const string Warning_GitNotFound_Body = "Warning_GitNotFound_Body";

    /// <summary>English: No author identity configured</summary>
    public const string Warning_NoIdentityConfigured_Title = "Warning_NoIdentityConfigured_Title";

    /// <summary>English: Neither user.name nor user.email is set anywhere, so git will refuse to create a commit. Set them globally, or per repository through a profile.</summary>
    public const string Warning_NoIdentityConfigured_Body = "Warning_NoIdentityConfigured_Body";

    /// <summary>English: {0} key</summary>
    public const string Plural_Keys_One = "Plural_Keys_One";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Few = "Plural_Keys_Few";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Many = "Plural_Keys_Many";

    /// <summary>English: {0} keys</summary>
    public const string Plural_Keys_Other = "Plural_Keys_Other";

    /// <summary>English: {0} identity</summary>
    public const string Plural_Identities_One = "Plural_Identities_One";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Few = "Plural_Identities_Few";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Many = "Plural_Identities_Many";

    /// <summary>English: {0} identities</summary>
    public const string Plural_Identities_Other = "Plural_Identities_Other";

    /// <summary>English: {0} agent</summary>
    public const string Plural_Agents_One = "Plural_Agents_One";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Few = "Plural_Agents_Few";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Many = "Plural_Agents_Many";

    /// <summary>English: {0} agents</summary>
    public const string Plural_Agents_Other = "Plural_Agents_Other";

    /// <summary>English: {0} credential</summary>
    public const string Plural_Credentials_One = "Plural_Credentials_One";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Few = "Plural_Credentials_Few";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Many = "Plural_Credentials_Many";

    /// <summary>English: {0} credentials</summary>
    public const string Plural_Credentials_Other = "Plural_Credentials_Other";

    /// <summary>English: {0} client</summary>
    public const string Plural_Clients_One = "Plural_Clients_One";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Few = "Plural_Clients_Few";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Many = "Plural_Clients_Many";

    /// <summary>English: {0} clients</summary>
    public const string Plural_Clients_Other = "Plural_Clients_Other";

    /// <summary>English: {0} warning</summary>
    public const string Plural_Warnings_One = "Plural_Warnings_One";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Few = "Plural_Warnings_Few";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Many = "Plural_Warnings_Many";

    /// <summary>English: {0} warnings</summary>
    public const string Plural_Warnings_Other = "Plural_Warnings_Other";

    /// <summary>English: This computer</summary>
    public const string Nav_ThisComputer = "Nav_ThisComputer";

    /// <summary>English: Snapshots &amp; rollback</summary>
    public const string Nav_Snapshots = "Nav_Snapshots";

    /// <summary>English: _File</summary>
    public const string Menu_File = "Menu_File";

    /// <summary>English: Rescan computer</summary>
    public const string Menu_File_Rescan = "Menu_File_Rescan";

    /// <summary>English: Open Profiles</summary>
    public const string Menu_File_OpenProfiles = "Menu_File_OpenProfiles";

    /// <summary>English: Export diagnostics…</summary>
    public const string Menu_File_ExportDiagnostics = "Menu_File_ExportDiagnostics";

    /// <summary>English: Exit</summary>
    public const string Menu_File_Exit = "Menu_File_Exit";

    /// <summary>English: _Edit</summary>
    public const string Menu_Edit = "Menu_Edit";

    /// <summary>English: _View</summary>
    public const string Menu_View = "Menu_View";

    /// <summary>English: Refresh</summary>
    public const string Menu_View_Refresh = "Menu_View_Refresh";

    /// <summary>English: Properties pane</summary>
    public const string Menu_View_PropertiesPane = "Menu_View_PropertiesPane";

    /// <summary>English: _Tools</summary>
    public const string Menu_Tools = "Menu_Tools";

    /// <summary>English: Profiles…</summary>
    public const string Menu_Tools_Profiles = "Menu_Tools_Profiles";

    /// <summary>English: Options…</summary>
    public const string Menu_Tools_Options = "Menu_Tools_Options";

    /// <summary>English: Snapshots &amp; rollback…</summary>
    public const string Menu_Tools_Snapshots = "Menu_Tools_Snapshots";

    /// <summary>English: _Help</summary>
    public const string Menu_Help = "Menu_Help";

    /// <summary>English: About GitVault…</summary>
    public const string Menu_Help_About = "Menu_Help_About";

    /// <summary>English: Preview</summary>
    public const string Toolbar_Preview = "Toolbar_Preview";

    /// <summary>English: Preview the selected profile&apos;s changes. Nothing is written.</summary>
    public const string Toolbar_PreviewTip = "Toolbar_PreviewTip";

    /// <summary>English: Apply the plan you reviewed</summary>
    public const string Toolbar_ApplyTip = "Toolbar_ApplyTip";

    /// <summary>English: Preview rolling back the last mutation</summary>
    public const string Toolbar_RollbackTip = "Toolbar_RollbackTip";

    /// <summary>English: Properties</summary>
    public const string Common_Properties = "Common_Properties";

    /// <summary>English: Search:</summary>
    public const string Common_SearchLabel = "Common_SearchLabel";

    /// <summary>English: Filter current view</summary>
    public const string Common_FilterCurrentView = "Common_FilterCurrentView";

    /// <summary>English: Select an item to see its properties.</summary>
    public const string Common_NoSelection = "Common_NoSelection";

    /// <summary>English: Save</summary>
    public const string Common_Save = "Common_Save";

    /// <summary>English: Add…</summary>
    public const string Common_Add = "Common_Add";

    /// <summary>English: Edit…</summary>
    public const string Common_Edit = "Common_Edit";

    /// <summary>English: Remove</summary>
    public const string Common_Remove = "Common_Remove";

    /// <summary>English: Browse…</summary>
    public const string Common_Browse = "Common_Browse";

    /// <summary>English: None</summary>
    public const string Common_None = "Common_None";

    /// <summary>English: Refresh</summary>
    public const string Common_Refresh = "Common_Refresh";

    /// <summary>English: Ready</summary>
    public const string Status_Ready = "Status_Ready";

    /// <summary>English: Scanning… read-only</summary>
    public const string Status_Scanning = "Status_Scanning";

    /// <summary>English: Scan completed in {0:F0} ms</summary>
    public const string Status_ScanCompleted = "Status_ScanCompleted";

    /// <summary>English: Insufficient permissions. Run elevated?</summary>
    public const string Status_InsufficientPermissions = "Status_InsufficientPermissions";

    /// <summary>English: Artifacts: {0} discovered</summary>
    public const string Status_Artifacts = "Status_Artifacts";

    /// <summary>English: Mode: Read-only</summary>
    public const string Status_Mode_ReadOnly = "Status_Mode_ReadOnly";

    /// <summary>English: Mode: Write pending</summary>
    public const string Status_Mode_PendingWrite = "Status_Mode_PendingWrite";

    /// <summary>English: Read-only scan complete</summary>
    public const string Status_ReadOnlyScanComplete = "Status_ReadOnlyScanComplete";

    /// <summary>English: No scan yet</summary>
    public const string Status_NoScanYet = "Status_NoScanYet";

    /// <summary>English: No pending writes</summary>
    public const string Status_NoPendingWrites = "Status_NoPendingWrites";

    /// <summary>English: A reviewed plan is waiting to be applied</summary>
    public const string Status_PendingWrite = "Status_PendingWrite";

    /// <summary>English: Viewing {0}</summary>
    public const string Status_Viewing = "Status_Viewing";

    /// <summary>English: Selected item copied</summary>
    public const string Status_Copied = "Status_Copied";

    /// <summary>English: Plan reviewed — Apply is now available</summary>
    public const string Status_PlanReviewed = "Status_PlanReviewed";

    /// <summary>English: Plan closed — nothing was applied</summary>
    public const string Status_PlanNotApplied = "Status_PlanNotApplied";

    /// <summary>English: Plan applied. A snapshot was created first.</summary>
    public const string Status_PlanApplied = "Status_PlanApplied";

    /// <summary>English: Rollback cancelled — nothing was changed</summary>
    public const string Status_RollbackCancelled = "Status_RollbackCancelled";

    /// <summary>English: Rollback complete: {0} files restored</summary>
    public const string Status_RollbackRestored = "Status_RollbackRestored";

    /// <summary>English: Profile created</summary>
    public const string Status_ProfileCreated = "Status_ProfileCreated";

    /// <summary>English: Profile saved</summary>
    public const string Status_ProfileSaved = "Status_ProfileSaved";

    /// <summary>English: Profile deleted</summary>
    public const string Status_ProfileDeleted = "Status_ProfileDeleted";

    /// <summary>English: Options saved</summary>
    public const string Status_OptionsSaved = "Status_OptionsSaved";

    /// <summary>English: Preview changes — activation</summary>
    public const string Dialog_PreviewActivation_Title = "Dialog_PreviewActivation_Title";

    /// <summary>English: Preview changes — deactivation</summary>
    public const string Dialog_PreviewDeactivation_Title = "Dialog_PreviewDeactivation_Title";

    /// <summary>English: No changes have been made.</summary>
    public const string Dialog_NothingWritten = "Dialog_NothingWritten";

    /// <summary>English: This is the dry-run plan. Apply stays disabled until you confirm that you have read it.</summary>
    public const string Dialog_ReviewBeforeApply = "Dialog_ReviewBeforeApply";

    /// <summary>English: I reviewed this plan</summary>
    public const string Dialog_ReviewedPlan = "Dialog_ReviewedPlan";

    /// <summary>English: Target scope</summary>
    public const string Dialog_TargetScope = "Dialog_TargetScope";

    /// <summary>English: Snapshot</summary>
    public const string Dialog_Snapshot = "Dialog_Snapshot";

    /// <summary>English: Snapshot #{0:D4} will be created before anything is written</summary>
    public const string Dialog_SnapshotWillBeCreated = "Dialog_SnapshotWillBeCreated";

    /// <summary>English: This plan cannot be applied.</summary>
    public const string Dialog_PlanBlocked = "Dialog_PlanBlocked";

    /// <summary>English: File permissions are preserved.</summary>
    public const string Dialog_Guarantee_Permissions = "Dialog_Guarantee_Permissions";

    /// <summary>English: No secret is placed on a command line.</summary>
    public const string Dialog_Guarantee_NoSecrets = "Dialog_Guarantee_NoSecrets";

    /// <summary>English: Preview rollback</summary>
    public const string Dialog_RollbackPreview_Title = "Dialog_RollbackPreview_Title";

    /// <summary>English: This lists what restoring the snapshot would do. Nothing is written until you confirm.</summary>
    public const string Dialog_RollbackExplains = "Dialog_RollbackExplains";

    /// <summary>English: Restore snapshot</summary>
    public const string Dialog_RestoreSnapshot = "Dialog_RestoreSnapshot";

    /// <summary>English: Files this would touch</summary>
    public const string Dialog_FilesRestored = "Dialog_FilesRestored";

    /// <summary>English: About GitVault</summary>
    public const string Dialog_About_Title = "Dialog_About_Title";

    /// <summary>English: Classic program icons: Tango Icon Library 0.8.90, public domain.</summary>
    public const string Dialog_About_IconLicense = "Dialog_About_IconLicense";

    /// <summary>English: Author identities discovered in Git configuration and known client settings.</summary>
    public const string Identities_Subtitle = "Identities_Subtitle";

    /// <summary>English: Private and public key artifacts. Private key material is never displayed or logged.</summary>
    public const string Keys_Subtitle = "Keys_Subtitle";

    /// <summary>English: Detected SSH agent processes and sockets.</summary>
    public const string Agents_Subtitle = "Agents_Subtitle";

    /// <summary>English: Credential-store metadata. Opaque secret stores remain opaque.</summary>
    public const string Credentials_Subtitle = "Credentials_Subtitle";

    /// <summary>English: Detected third-party Git GUI clients and their per-client configuration.</summary>
    public const string Clients_Subtitle = "Clients_Subtitle";

    /// <summary>English: Discovered repositories and their effective identity overrides.</summary>
    public const string Repositories_Subtitle = "Repositories_Subtitle";

    /// <summary>English: Operational log. Secrets are redacted before every sink.</summary>
    public const string Logs_Subtitle = "Logs_Subtitle";

    /// <summary>English: Reusable Git identity configurations, activated through preview and apply.</summary>
    public const string Profiles_Subtitle = "Profiles_Subtitle";

    /// <summary>English: Language, appearance, discovery roots and diagnostics.</summary>
    public const string Settings_Subtitle = "Settings_Subtitle";

    /// <summary>English: Byte-for-byte snapshots taken before every mutation.</summary>
    public const string Snapshots_Subtitle = "Snapshots_Subtitle";

    /// <summary>English: Snapshots &amp; rollback</summary>
    public const string Snapshots_Title = "Snapshots_Title";

    /// <summary>English: No snapshots yet. One is taken automatically before any change.</summary>
    public const string Snapshots_Empty = "Snapshots_Empty";

    /// <summary>English: Snapshot</summary>
    public const string Snapshots_Column_Snapshot = "Snapshots_Column_Snapshot";

    /// <summary>English: Created</summary>
    public const string Snapshots_Column_Created = "Snapshots_Column_Created";

    /// <summary>English: Operation</summary>
    public const string Snapshots_Column_Operation = "Snapshots_Column_Operation";

    /// <summary>English: Target</summary>
    public const string Snapshots_Column_Target = "Snapshots_Column_Target";

    /// <summary>English: State</summary>
    public const string Snapshots_Column_State = "Snapshots_Column_State";

    /// <summary>English: Profile</summary>
    public const string Snapshots_Column_Profile = "Snapshots_Column_Profile";

    /// <summary>English: Action</summary>
    public const string Snapshots_Column_Action = "Snapshots_Column_Action";

    /// <summary>English: Files</summary>
    public const string Snapshots_Detail_Files = "Snapshots_Detail_Files";

    /// <summary>English: Activate {0}</summary>
    public const string Snapshots_Operation_Activate = "Snapshots_Operation_Activate";

    /// <summary>English: Deactivate {0}</summary>
    public const string Snapshots_Operation_Deactivate = "Snapshots_Operation_Deactivate";

    /// <summary>English: Unrecorded operation</summary>
    public const string Snapshots_Operation_Unknown = "Snapshots_Operation_Unknown";

    /// <summary>English: Available</summary>
    public const string Snapshots_State_Available = "Snapshots_State_Available";

    /// <summary>English: Incomplete</summary>
    public const string Snapshots_State_Incomplete = "Snapshots_State_Incomplete";

    /// <summary>English: Restore</summary>
    public const string Snapshots_Action_Restore = "Snapshots_Action_Restore";

    /// <summary>English: Recreate</summary>
    public const string Snapshots_Action_Recreate = "Snapshots_Action_Recreate";

    /// <summary>English: Delete again</summary>
    public const string Snapshots_Action_Delete = "Snapshots_Action_Delete";

    /// <summary>English: Unchanged</summary>
    public const string Snapshots_Action_Unchanged = "Snapshots_Action_Unchanged";

    /// <summary>English: The newest {0} snapshots are kept; older ones are pruned automatically.</summary>
    public const string Snapshots_Retention = "Snapshots_Retention";

    /// <summary>English: Preview rollback…</summary>
    public const string Snapshots_PreviewRollback = "Snapshots_PreviewRollback";

    /// <summary>English: Scan roots</summary>
    public const string Options_Group_ScanRoots = "Options_Group_ScanRoots";

    /// <summary>English: Custom SSH key folders</summary>
    public const string Options_Group_KeyFolders = "Options_Group_KeyFolders";

    /// <summary>English: Appearance and language</summary>
    public const string Options_Group_Appearance = "Options_Group_Appearance";

    /// <summary>English: Behaviour</summary>
    public const string Options_Group_Behaviour = "Options_Group_Behaviour";

    /// <summary>English: Add scan root</summary>
    public const string Options_AddScanRoot = "Options_AddScanRoot";

    /// <summary>English: Edit scan root</summary>
    public const string Options_EditScanRoot = "Options_EditScanRoot";

    /// <summary>English: Add key folder</summary>
    public const string Options_AddKeyFolder = "Options_AddKeyFolder";

    /// <summary>English: Edit key folder</summary>
    public const string Options_EditKeyFolder = "Options_EditKeyFolder";

    /// <summary>English: Path:</summary>
    public const string Options_Field_Path = "Options_Field_Path";

    /// <summary>English: Depth:</summary>
    public const string Options_Field_Depth = "Options_Field_Depth";

    /// <summary>English: Material:</summary>
    public const string Options_Field_Material = "Options_Field_Material";

    /// <summary>English: Enabled:</summary>
    public const string Options_Field_Enabled = "Options_Field_Enabled";

    /// <summary>English: Recursive</summary>
    public const string Options_Depth_Recursive = "Options_Depth_Recursive";

    /// <summary>English: Top-level only</summary>
    public const string Options_Depth_TopLevel = "Options_Depth_TopLevel";

    /// <summary>English: Private + public</summary>
    public const string Options_Mode_PrivateAndPublic = "Options_Mode_PrivateAndPublic";

    /// <summary>English: Public only</summary>
    public const string Options_Mode_PublicOnly = "Options_Mode_PublicOnly";

    /// <summary>English: Scan this root</summary>
    public const string Options_ScanThisRoot = "Options_ScanThisRoot";

    /// <summary>English: Scan this folder</summary>
    public const string Options_ScanThisFolder = "Options_ScanThisFolder";

    /// <summary>English: Enabled</summary>
    public const string Options_State_Enabled = "Options_State_Enabled";

    /// <summary>English: Disabled</summary>
    public const string Options_State_Disabled = "Options_State_Disabled";

    /// <summary>English: Editing these lists changes GitVault&apos;s own settings only. No repository, key or credential is modified.</summary>
    public const string Options_SettingsOnlyNote = "Options_SettingsOnlyNote";

    /// <summary>English: GitVault reads key files and never writes to them.</summary>
    public const string Options_KeysReadOnlyNote = "Options_KeysReadOnlyNote";

    /// <summary>English: Choose a folder to search for repositories</summary>
    public const string Options_PickScanRoot = "Options_PickScanRoot";

    /// <summary>English: Choose a folder to search for SSH keys</summary>
    public const string Options_PickKeyFolder = "Options_PickKeyFolder";

    /// <summary>English: Remove scan root</summary>
    public const string Options_RemoveScanRoot_Title = "Options_RemoveScanRoot_Title";

    /// <summary>English: Stop searching {0} for repositories?</summary>
    public const string Options_RemoveScanRoot_Message = "Options_RemoveScanRoot_Message";

    /// <summary>English: Remove key folder</summary>
    public const string Options_RemoveKeyFolder_Title = "Options_RemoveKeyFolder_Title";

    /// <summary>English: Stop searching {0} for SSH keys?</summary>
    public const string Options_RemoveKeyFolder_Message = "Options_RemoveKeyFolder_Message";

    /// <summary>English: No scan roots configured.</summary>
    public const string Options_NoScanRoots = "Options_NoScanRoots";

    /// <summary>English: No extra key folders configured. The default locations are always searched.</summary>
    public const string Options_NoKeyFolders = "Options_NoKeyFolders";

    /// <summary>English: Profile editor</summary>
    public const string Profiles_Editor = "Profiles_Editor";

    /// <summary>English: Activation</summary>
    public const string Profiles_Activation = "Profiles_Activation";

    /// <summary>English: Profile name:</summary>
    public const string Profiles_Field_Name = "Profiles_Field_Name";

    /// <summary>English: Identity:</summary>
    public const string Profiles_Field_Identity = "Profiles_Field_Identity";

    /// <summary>English: SSH key:</summary>
    public const string Profiles_Field_SshKey = "Profiles_Field_SshKey";

    /// <summary>English: Credential helper:</summary>
    public const string Profiles_Field_Helper = "Profiles_Field_Helper";

    /// <summary>English: Stored scope:</summary>
    public const string Profiles_Field_StoredScope = "Profiles_Field_StoredScope";

    /// <summary>English: Repository path:</summary>
    public const string Profiles_Field_RepositoryPath = "Profiles_Field_RepositoryPath";

    /// <summary>English: Pin the key with core.sshCommand</summary>
    public const string Profiles_Field_WriteSshCommand = "Profiles_Field_WriteSshCommand";

    /// <summary>English: Stored scope</summary>
    public const string Profiles_Column_StoredScope = "Profiles_Column_StoredScope";

    /// <summary>English: Repository</summary>
    public const string Profiles_Repository = "Profiles_Repository";

    /// <summary>English: Plan state</summary>
    public const string Profiles_State = "Profiles_State";

    /// <summary>English: Not previewed</summary>
    public const string Profiles_State_NotPreviewed = "Profiles_State_NotPreviewed";

    /// <summary>English: Previewed, not reviewed</summary>
    public const string Profiles_State_NotReviewed = "Profiles_State_NotReviewed";

    /// <summary>English: Reviewed</summary>
    public const string Profiles_State_Reviewed = "Profiles_State_Reviewed";

    /// <summary>English: New…</summary>
    public const string Profiles_New = "Profiles_New";

    /// <summary>English: Save profile</summary>
    public const string Profiles_Save = "Profiles_Save";

    /// <summary>English: Delete</summary>
    public const string Profiles_Delete = "Profiles_Delete";

    /// <summary>English: New profile</summary>
    public const string Profiles_New_Title = "Profiles_New_Title";

    /// <summary>English: No identity has been discovered yet. Run a scan first.</summary>
    public const string Profiles_New_NoIdentities = "Profiles_New_NoIdentities";

    /// <summary>English: Delete profile</summary>
    public const string Profiles_Delete_Title = "Profiles_Delete_Title";

    /// <summary>English: Delete the profile &quot;{0}&quot;?</summary>
    public const string Profiles_Delete_Message = "Profiles_Delete_Message";

    /// <summary>English: This removes the profile only. No identity, key or credential is deleted, and nothing already applied is undone.</summary>
    public const string Profiles_Delete_Detail = "Profiles_Delete_Detail";

    /// <summary>English: Preview activation…</summary>
    public const string Profiles_PreviewActivation = "Profiles_PreviewActivation";

    /// <summary>English: Preview deactivation…</summary>
    public const string Profiles_PreviewDeactivation = "Profiles_PreviewDeactivation";

    /// <summary>English: A snapshot is created before any mutation, and Apply stays disabled until a dry-run plan has been reviewed.</summary>
    public const string Profiles_SnapshotNote = "Profiles_SnapshotNote";

    /// <summary>English: The scope opens with the value saved on the profile rather than defaulting to Global.</summary>
    public const string Profiles_StoredScopeNote = "Profiles_StoredScopeNote";

    /// <summary>English: Unsaved changes</summary>
    public const string Profiles_UnsavedChanges = "Profiles_UnsavedChanges";

    /// <summary>English: Platform</summary>
    public const string Dashboard_Detail_Platform = "Dashboard_Detail_Platform";

    /// <summary>English: Architecture</summary>
    public const string Dashboard_Detail_Architecture = "Dashboard_Detail_Architecture";

    /// <summary>English: Git</summary>
    public const string Dashboard_Detail_Git = "Dashboard_Detail_Git";

    /// <summary>English: Settings folder</summary>
    public const string Dashboard_Detail_AppData = "Dashboard_Detail_AppData";

    /// <summary>English: Finding</summary>
    public const string Dashboard_Detail_Finding = "Dashboard_Detail_Finding";

    /// <summary>English: Subject</summary>
    public const string Dashboard_Detail_Subject = "Dashboard_Detail_Subject";

    /// <summary>English: Severity</summary>
    public const string Dashboard_Detail_Severity = "Dashboard_Detail_Severity";

    /// <summary>English: Effective Git identity</summary>
    public const string Dashboard_Group_Effective = "Dashboard_Group_Effective";

    /// <summary>English: Attention</summary>
    public const string Dashboard_Group_Attention = "Dashboard_Group_Attention";

    /// <summary>English: High</summary>
    public const string Severity_High = "Severity_High";

    /// <summary>English: Medium</summary>
    public const string Severity_Medium = "Severity_Medium";

    /// <summary>English: Low</summary>
    public const string Severity_Low = "Severity_Low";

    /// <summary>English: Private material</summary>
    public const string Keys_Detail_PrivateMaterial = "Keys_Detail_PrivateMaterial";

    /// <summary>English: Hidden by design</summary>
    public const string Keys_HiddenByDesign = "Keys_HiddenByDesign";

    /// <summary>English: Target</summary>
    public const string Credentials_Detail_Target = "Credentials_Detail_Target";

    /// <summary>English: Storage</summary>
    public const string Credentials_Detail_Storage = "Credentials_Detail_Storage";

    /// <summary>English: Secret value</summary>
    public const string Credentials_Detail_SecretValue = "Credentials_Detail_SecretValue";

    /// <summary>English: Protected by the OS</summary>
    public const string Credentials_ProtectedBadge = "Credentials_ProtectedBadge";

    /// <summary>English: Not read</summary>
    public const string Credentials_NotRead = "Credentials_NotRead";

    /// <summary>English: Endpoint</summary>
    public const string Agents_Detail_Endpoint = "Agents_Detail_Endpoint";

    /// <summary>English: Key loading</summary>
    public const string Agents_Detail_Writable = "Agents_Detail_Writable";

    /// <summary>English: Read-only</summary>
    public const string Agents_ReadOnlyBadge = "Agents_ReadOnlyBadge";

    /// <summary>English: Supported</summary>
    public const string Agents_WritableBadge = "Agents_WritableBadge";

    /// <summary>English: Agent</summary>
    public const string Agents_Column_Agent = "Agents_Column_Agent";

    /// <summary>English: State</summary>
    public const string Agents_Column_State = "Agents_Column_State";

    /// <summary>English: Source</summary>
    public const string Agents_Column_Source = "Agents_Column_Source";

    /// <summary>English: Client</summary>
    public const string Clients_Column_Client = "Clients_Column_Client";

    /// <summary>English: Version</summary>
    public const string Clients_Column_Version = "Clients_Column_Version";

    /// <summary>English: Secret storage</summary>
    public const string Clients_Column_Storage = "Clients_Column_Storage";

    /// <summary>English: Time</summary>
    public const string Logs_Column_Time = "Logs_Column_Time";

    /// <summary>English: Secrets</summary>
    public const string Logs_Detail_Secrets = "Logs_Detail_Secrets";

    /// <summary>English: Exception</summary>
    public const string Logs_Detail_Exception = "Logs_Detail_Exception";

    /// <summary>English: Redacted before every sink</summary>
    public const string Logs_Redacted = "Logs_Redacted";

    /// <summary>English: #{0:D4}</summary>
    public const string Snapshots_Number = "Snapshots_Number";

    /// <summary>English: Path</summary>
    public const string Options_Column_Path = "Options_Column_Path";

    /// <summary>English: Depth</summary>
    public const string Options_Column_Depth = "Options_Column_Depth";

    /// <summary>English: Material</summary>
    public const string Options_Column_Material = "Options_Column_Material";

    /// <summary>English: Enabled</summary>
    public const string Options_Column_Enabled = "Options_Column_Enabled";

    /// <summary>All keys, in declaration order.</summary>
    public static IReadOnlyList<string> All { get; } =
    [
        App_Title,
        App_Subtitle,
        App_WindowTitle,
        Nav_Dashboard,
        Nav_Identities,
        Nav_Keys,
        Nav_Agents,
        Nav_Credentials,
        Nav_Clients,
        Nav_Profiles,
        Nav_Repositories,
        Nav_Settings,
        Nav_Logs,
        Common_Rescan,
        Common_Search,
        Common_Cancel,
        Common_Ok,
        Common_Close,
        Common_Copy,
        Common_Apply,
        Common_Working,
        Common_NoData,
        Common_Details,
        Common_WhatDoesThisMean,
        Common_Yes,
        Common_No,
        Common_Never,
        Common_ListSeparator,
        Dashboard_Title,
        Dashboard_Subtitle,
        Dashboard_Card_Identities,
        Dashboard_Card_Keys,
        Dashboard_Card_Agents,
        Dashboard_Card_Credentials,
        Dashboard_Card_Clients,
        Dashboard_ActiveIdentity,
        Dashboard_NoScanYet,
        Dashboard_FixAllSafe,
        Dashboard_Warnings,
        Dashboard_ScanDuration,
        Dashboard_ProbeMatrix,
        Dashboard_Env_Os,
        Dashboard_Env_Cpu,
        Dashboard_Env_AppData,
        Dashboard_Env_Git,
        Dashboard_Env_GitPathAndVersion,
        Dashboard_Scanning,
        Identities_Title,
        Identities_Column_Name,
        Identities_Column_Email,
        Identities_Column_Source,
        Identities_Column_Hosts,
        Identities_Column_Scope,
        Identities_Column_Confidence,
        Identities_Column_SigningKey,
        Identities_Empty,
        Identities_Effective_Title,
        Identities_Effective_Key,
        Identities_Effective_Value,
        Identities_Effective_WinningScope,
        Identities_Effective_Unset,
        Identities_Effective_OverriddenIn,
        Identities_Detail_Occurrences,
        Scope_System,
        Scope_Global,
        Scope_Local,
        Scope_Worktree,
        Scope_Command,
        Scope_Unknown,
        Confidence_Certain,
        Confidence_Probable,
        Confidence_Heuristic,
        Source_GitSystemConfig,
        Source_GitGlobalConfig,
        Source_RepoLocal,
        Source_RepoWorktree,
        Source_GitIncludedFile,
        Source_Unknown,
        Keys_Title,
        Keys_Column_Algorithm,
        Keys_Column_Fingerprint,
        Keys_Column_Comment,
        Keys_Column_Path,
        Keys_Column_Format,
        Keys_Encrypted,
        Keys_NotEncrypted,
        Keys_InAgent,
        Keys_Empty,
        Keys_Column_Bits,
        Keys_Column_Protection,
        Keys_Detail_PublicKey,
        Keys_Detail_Permissions,
        Keys_Detail_KdfRounds,
        Keys_Hardware,
        Keys_CopyPublicKey,
        Keys_CopyFingerprint,
        Keys_RevealInFileManager,
        Keys_Copied,
        Format_OpenSsh,
        Format_Pem,
        Format_Pkcs8,
        Format_Ppk2,
        Format_Ppk3,
        Format_PublicOnly,
        Format_Unknown,
        Agents_Title,
        Agents_Endpoint,
        Agents_Running,
        Agents_Stopped,
        Agents_Locked,
        Agents_LoadedKeys,
        Agents_ReadOnly,
        Agents_ShellSnippet,
        Agents_Empty,
        Agents_Column_Algorithm,
        Agents_Column_Fingerprint,
        Agents_Column_Comment,
        Agents_RemoveKey,
        Agents_RemoveAll,
        Agents_RemoveAllConfirm,
        Agents_Lock,
        Agents_Unlock,
        Agents_AddKey,
        Agents_AddKey_NeedsPassphrase,
        Agents_CopySnippet,
        Agents_Shell,
        AgentKind_OpenSshUnix,
        AgentKind_OpenSshWindowsPipe,
        AgentKind_Pageant,
        AgentKind_GpgAgent,
        AgentKind_OnePassword,
        AgentKind_KeeAgent,
        AgentKind_WslRelay,
        AgentKind_Unknown,
        Credentials_Title,
        Credentials_Column_Host,
        Credentials_Column_UserName,
        Credentials_Column_Protocol,
        Credentials_Column_Vault,
        Credentials_Column_Client,
        Credentials_Column_LastWrite,
        Credentials_Reveal,
        Credentials_Empty,
        Credentials_Column_Target,
        Credentials_ShowAll,
        Credentials_RevealConfirm,
        Credentials_Hide,
        Credentials_CopySecret,
        Credentials_HidingIn,
        Credentials_ClipboardNote,
        Credentials_PlaintextBadge,
        Credentials_TestWithGit,
        Vault_WindowsCredentialManager,
        Vault_MacKeychain,
        Vault_SecretService,
        Vault_KWallet,
        Vault_GitCredentialsFile,
        Vault_GcmPlaintext,
        Vault_GcmDpapi,
        Vault_GcmGpg,
        Vault_GitKrakenBox,
        Vault_GitCredentialCache,
        Vault_Unknown,
        Clients_Title,
        Clients_Version,
        Clients_InstallPath,
        Clients_ConfigRoots,
        Clients_Opaque,
        Clients_Empty,
        Clients_Accounts,
        Clients_BoundKeys,
        Clients_SshCommand,
        Clients_OpenConfigFolder,
        Clients_CredentialsCount,
        Warning_TortoiseGitMissingKey_Title,
        Warning_TortoiseGitMissingKey_Body,
        Warning_WslSeparateKeys_Title,
        Warning_WslSeparateKeys_Body,
        Profiles_Title,
        Profiles_Activate_Button,
        Profiles_Deactivate_Button,
        Profiles_Scope_Global,
        Profiles_Scope_System,
        Profiles_Scope_Repository,
        Profiles_DryRun,
        Profiles_Rollback,
        Profiles_RecentActivations,
        Profiles_Empty,
        Profiles_Preview,
        Profiles_PlannedChanges,
        Profiles_NothingToDo,
        Profiles_ApplyDryRunFirst,
        Profiles_Applied,
        Profiles_Blocked,
        Profiles_BlockedWithReasons,
        Profiles_Column_Name,
        Profiles_Column_Identity,
        Profiles_Column_Helper,
        Profiles_IsActive,
        Repositories_Scan,
        Repositories_Scanning,
        Repositories_NoRoots,
        Repositories_Column_Name,
        Identities_NameAndEmail,
        Repositories_Title,
        Repositories_AddRoot,
        Repositories_Column_Path,
        Repositories_Column_EffectiveIdentity,
        Repositories_Column_Remote,
        Repositories_Empty,
        Settings_Title,
        Settings_Language,
        Settings_Theme,
        Settings_Theme_System,
        Settings_Theme_Light,
        Settings_Theme_Dark,
        Settings_DryRunDefault,
        Settings_WatchForChanges,
        Settings_LogLevel,
        Settings_OpenLogsFolder,
        Settings_ScanRoots,
        Settings_CustomKeyFolders,
        Settings_RevealPolicy,
        Settings_AutoHideSeconds,
        Settings_ClipboardClearSeconds,
        Settings_Diagnostics,
        Settings_PreviewDiagnostics,
        Settings_SaveDiagnostics,
        Settings_DiagnosticsNote,
        Settings_DiagnosticsSaved,
        Settings_Telemetry,
        Settings_TelemetryNone,
        Logs_Title,
        Logs_Filter,
        Logs_Clear,
        Logs_Column_Timestamp,
        Logs_Column_Level,
        Logs_Column_Message,
        Status_Ok,
        Status_NotInstalled,
        Status_AccessDenied,
        Status_Timeout,
        Status_ParseError,
        Status_NotApplicable,
        Status_Failed,
        Warning_KeyWorldReadable_Title,
        Warning_KeyWorldReadable_Body,
        Warning_RsaTooShort_Title,
        Warning_RsaTooShort_Body,
        Warning_DsaDeprecated_Title,
        Warning_DsaDeprecated_Body,
        Warning_KeyNoPassphrase_Title,
        Warning_KeyNoPassphrase_Body,
        Warning_OrphanedPublicKey_Title,
        Warning_OrphanedPublicKey_Body,
        Warning_PlaintextCredentialStore_Title,
        Warning_PlaintextCredentialStore_Body,
        Warning_MissingPublicKey_Title,
        Warning_MissingPublicKey_Body,
        Warning_KeyIntegrityFailed_Title,
        Warning_KeyIntegrityFailed_Body,
        Warning_AgentNotRunning_Title,
        Warning_AgentNotRunning_Body,
        Warning_GitNotFound_Title,
        Warning_GitNotFound_Body,
        Warning_NoIdentityConfigured_Title,
        Warning_NoIdentityConfigured_Body,
        Plural_Keys_One,
        Plural_Keys_Few,
        Plural_Keys_Many,
        Plural_Keys_Other,
        Plural_Identities_One,
        Plural_Identities_Few,
        Plural_Identities_Many,
        Plural_Identities_Other,
        Plural_Agents_One,
        Plural_Agents_Few,
        Plural_Agents_Many,
        Plural_Agents_Other,
        Plural_Credentials_One,
        Plural_Credentials_Few,
        Plural_Credentials_Many,
        Plural_Credentials_Other,
        Plural_Clients_One,
        Plural_Clients_Few,
        Plural_Clients_Many,
        Plural_Clients_Other,
        Plural_Warnings_One,
        Plural_Warnings_Few,
        Plural_Warnings_Many,
        Plural_Warnings_Other,
        Nav_ThisComputer,
        Nav_Snapshots,
        Menu_File,
        Menu_File_Rescan,
        Menu_File_OpenProfiles,
        Menu_File_ExportDiagnostics,
        Menu_File_Exit,
        Menu_Edit,
        Menu_View,
        Menu_View_Refresh,
        Menu_View_PropertiesPane,
        Menu_Tools,
        Menu_Tools_Profiles,
        Menu_Tools_Options,
        Menu_Tools_Snapshots,
        Menu_Help,
        Menu_Help_About,
        Toolbar_Preview,
        Toolbar_PreviewTip,
        Toolbar_ApplyTip,
        Toolbar_RollbackTip,
        Common_Properties,
        Common_SearchLabel,
        Common_FilterCurrentView,
        Common_NoSelection,
        Common_Save,
        Common_Add,
        Common_Edit,
        Common_Remove,
        Common_Browse,
        Common_None,
        Common_Refresh,
        Status_Ready,
        Status_Scanning,
        Status_ScanCompleted,
        Status_InsufficientPermissions,
        Status_Artifacts,
        Status_Mode_ReadOnly,
        Status_Mode_PendingWrite,
        Status_ReadOnlyScanComplete,
        Status_NoScanYet,
        Status_NoPendingWrites,
        Status_PendingWrite,
        Status_Viewing,
        Status_Copied,
        Status_PlanReviewed,
        Status_PlanNotApplied,
        Status_PlanApplied,
        Status_RollbackCancelled,
        Status_RollbackRestored,
        Status_ProfileCreated,
        Status_ProfileSaved,
        Status_ProfileDeleted,
        Status_OptionsSaved,
        Dialog_PreviewActivation_Title,
        Dialog_PreviewDeactivation_Title,
        Dialog_NothingWritten,
        Dialog_ReviewBeforeApply,
        Dialog_ReviewedPlan,
        Dialog_TargetScope,
        Dialog_Snapshot,
        Dialog_SnapshotWillBeCreated,
        Dialog_PlanBlocked,
        Dialog_Guarantee_Permissions,
        Dialog_Guarantee_NoSecrets,
        Dialog_RollbackPreview_Title,
        Dialog_RollbackExplains,
        Dialog_RestoreSnapshot,
        Dialog_FilesRestored,
        Dialog_About_Title,
        Dialog_About_IconLicense,
        Identities_Subtitle,
        Keys_Subtitle,
        Agents_Subtitle,
        Credentials_Subtitle,
        Clients_Subtitle,
        Repositories_Subtitle,
        Logs_Subtitle,
        Profiles_Subtitle,
        Settings_Subtitle,
        Snapshots_Subtitle,
        Snapshots_Title,
        Snapshots_Empty,
        Snapshots_Column_Snapshot,
        Snapshots_Column_Created,
        Snapshots_Column_Operation,
        Snapshots_Column_Target,
        Snapshots_Column_State,
        Snapshots_Column_Profile,
        Snapshots_Column_Action,
        Snapshots_Detail_Files,
        Snapshots_Operation_Activate,
        Snapshots_Operation_Deactivate,
        Snapshots_Operation_Unknown,
        Snapshots_State_Available,
        Snapshots_State_Incomplete,
        Snapshots_Action_Restore,
        Snapshots_Action_Recreate,
        Snapshots_Action_Delete,
        Snapshots_Action_Unchanged,
        Snapshots_Retention,
        Snapshots_PreviewRollback,
        Options_Group_ScanRoots,
        Options_Group_KeyFolders,
        Options_Group_Appearance,
        Options_Group_Behaviour,
        Options_AddScanRoot,
        Options_EditScanRoot,
        Options_AddKeyFolder,
        Options_EditKeyFolder,
        Options_Field_Path,
        Options_Field_Depth,
        Options_Field_Material,
        Options_Field_Enabled,
        Options_Depth_Recursive,
        Options_Depth_TopLevel,
        Options_Mode_PrivateAndPublic,
        Options_Mode_PublicOnly,
        Options_ScanThisRoot,
        Options_ScanThisFolder,
        Options_State_Enabled,
        Options_State_Disabled,
        Options_SettingsOnlyNote,
        Options_KeysReadOnlyNote,
        Options_PickScanRoot,
        Options_PickKeyFolder,
        Options_RemoveScanRoot_Title,
        Options_RemoveScanRoot_Message,
        Options_RemoveKeyFolder_Title,
        Options_RemoveKeyFolder_Message,
        Options_NoScanRoots,
        Options_NoKeyFolders,
        Profiles_Editor,
        Profiles_Activation,
        Profiles_Field_Name,
        Profiles_Field_Identity,
        Profiles_Field_SshKey,
        Profiles_Field_Helper,
        Profiles_Field_StoredScope,
        Profiles_Field_RepositoryPath,
        Profiles_Field_WriteSshCommand,
        Profiles_Column_StoredScope,
        Profiles_Repository,
        Profiles_State,
        Profiles_State_NotPreviewed,
        Profiles_State_NotReviewed,
        Profiles_State_Reviewed,
        Profiles_New,
        Profiles_Save,
        Profiles_Delete,
        Profiles_New_Title,
        Profiles_New_NoIdentities,
        Profiles_Delete_Title,
        Profiles_Delete_Message,
        Profiles_Delete_Detail,
        Profiles_PreviewActivation,
        Profiles_PreviewDeactivation,
        Profiles_SnapshotNote,
        Profiles_StoredScopeNote,
        Profiles_UnsavedChanges,
        Dashboard_Detail_Platform,
        Dashboard_Detail_Architecture,
        Dashboard_Detail_Git,
        Dashboard_Detail_AppData,
        Dashboard_Detail_Finding,
        Dashboard_Detail_Subject,
        Dashboard_Detail_Severity,
        Dashboard_Group_Effective,
        Dashboard_Group_Attention,
        Severity_High,
        Severity_Medium,
        Severity_Low,
        Keys_Detail_PrivateMaterial,
        Keys_HiddenByDesign,
        Credentials_Detail_Target,
        Credentials_Detail_Storage,
        Credentials_Detail_SecretValue,
        Credentials_ProtectedBadge,
        Credentials_NotRead,
        Agents_Detail_Endpoint,
        Agents_Detail_Writable,
        Agents_ReadOnlyBadge,
        Agents_WritableBadge,
        Agents_Column_Agent,
        Agents_Column_State,
        Agents_Column_Source,
        Clients_Column_Client,
        Clients_Column_Version,
        Clients_Column_Storage,
        Logs_Column_Time,
        Logs_Detail_Secrets,
        Logs_Detail_Exception,
        Logs_Redacted,
        Snapshots_Number,
        Options_Column_Path,
        Options_Column_Depth,
        Options_Column_Material,
        Options_Column_Enabled,
    ];
}
